# Generated by Django 5.2.9 on 2025-12-13 02:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lgpd", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoSeguranca",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=200)),
                (
                    "tipo_sistema",
                    models.CharField(
                        choices=[
                            ("servidor", "Servidor"),
                            ("aplicacao", "Aplicação"),
                            ("banco_dados", "Banco de Dados"),
                            ("rede", "Dispositivo de Rede"),
                            ("estacao", "Estação de Trabalho"),
                            ("container", "Container"),
                            ("cloud", "Serviço Cloud"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "configuracoes",
                    models.JSONField(
                        default=dict,
                        help_text="Configurações de segurança em formato JSON",
                    ),
                ),
                ("versao", models.CharField(max_length=20)),
                ("data_aprovacao", models.DateField()),
                ("proxima_revisao", models.DateField()),
                (
                    "frameworks",
                    models.JSONField(
                        default=list,
                        help_text="Frameworks de referência (CIS, NIST, etc.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Segurança",
                "verbose_name_plural": "Configurações de Segurança",
            },
        ),
        migrations.CreateModel(
            name="RegraDeteccao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("comportamento", "Análise de Comportamento"),
                            ("assinatura", "Baseado em Assinatura"),
                            ("anomalia", "Detecção de Anomalia"),
                            ("correlacao", "Correlação de Eventos"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "condicoes",
                    models.JSONField(
                        default=dict, help_text="Condições para ativação da regra"
                    ),
                ),
                (
                    "severidade",
                    models.CharField(
                        choices=[
                            ("info", "Informativo"),
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "acoes",
                    models.JSONField(
                        default=list, help_text="Ações a executar quando ativada"
                    ),
                ),
                ("habilitada", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Regra de Detecção",
                "verbose_name_plural": "Regras de Detecção",
            },
        ),
        migrations.CreateModel(
            name="TreinamentoSeguranca",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("conscientizacao", "Conscientização"),
                            ("tecnico", "Técnico"),
                            ("phishing", "Simulação de Phishing"),
                            ("incidentes", "Resposta a Incidentes"),
                            ("privacidade", "Privacidade de Dados"),
                        ],
                        max_length=30,
                    ),
                ),
                ("obrigatorio", models.BooleanField(default=False)),
                ("publico_alvo", models.JSONField(default=list)),
                ("carga_horaria", models.IntegerField(help_text="Duração em minutos")),
                ("validade_dias", models.IntegerField(default=365)),
            ],
            options={
                "verbose_name": "Treinamento de Segurança",
                "verbose_name_plural": "Treinamentos de Segurança",
            },
        ),
        migrations.CreateModel(
            name="AcaoResposta",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("contencao", "Contenção"),
                            ("erradicacao", "Erradicação"),
                            ("recuperacao", "Recuperação"),
                            ("comunicacao", "Comunicação"),
                            ("forense", "Análise Forense"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descricao", models.TextField()),
                ("data_inicio", models.DateTimeField()),
                ("data_conclusao", models.DateTimeField(blank=True, null=True)),
                ("resultado", models.TextField(blank=True)),
                ("evidencias", models.JSONField(default=list)),
                (
                    "executado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incidente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acoes_resposta",
                        to="lgpd.incidenteseguranca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ação de Resposta",
                "verbose_name_plural": "Ações de Resposta",
            },
        ),
        migrations.CreateModel(
            name="AtivoInformacao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("dados", "Dados/Informações"),
                            ("software", "Software/Aplicação"),
                            ("hardware", "Hardware"),
                            ("rede", "Infraestrutura de Rede"),
                            ("pessoas", "Pessoas/Conhecimento"),
                            ("servico", "Serviço"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "classificacao",
                    models.CharField(
                        choices=[
                            ("publico", "Público"),
                            ("interno", "Interno"),
                            ("confidencial", "Confidencial"),
                            ("restrito", "Restrito"),
                        ],
                        max_length=20,
                    ),
                ),
                ("localizacao", models.CharField(max_length=200)),
                (
                    "ambiente",
                    models.CharField(
                        choices=[
                            ("producao", "Produção"),
                            ("homologacao", "Homologação"),
                            ("desenvolvimento", "Desenvolvimento"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "valor_negocio",
                    models.CharField(
                        choices=[
                            ("baixo", "Baixo"),
                            ("medio", "Médio"),
                            ("alto", "Alto"),
                            ("critico", "Crítico"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "custodiante",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ativos_custodiante",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dependencias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dependentes",
                        to="nist.ativoinformacao",
                    ),
                ),
                (
                    "proprietario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ativos_proprietario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ativo de Informação",
                "verbose_name_plural": "Ativos de Informação",
            },
        ),
        migrations.CreateModel(
            name="AvaliacaoRisco",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("ameaca", models.CharField(max_length=200)),
                ("vulnerabilidade", models.CharField(max_length=200)),
                (
                    "probabilidade",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="1=Raro, 2=Improvável, 3=Possível, 4=Provável, 5=Quase Certo",
                    ),
                ),
                (
                    "impacto",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="1=Insignificante, 2=Menor, 3=Moderado, 4=Maior, 5=Catastrófico",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identificado", "Identificado"),
                            ("analisado", "Analisado"),
                            ("tratado", "Tratado"),
                            ("aceito", "Aceito"),
                            ("monitorado", "Monitorado"),
                        ],
                        default="identificado",
                        max_length=20,
                    ),
                ),
                (
                    "estrategia_tratamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mitigar", "Mitigar"),
                            ("transferir", "Transferir"),
                            ("aceitar", "Aceitar"),
                            ("evitar", "Evitar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("plano_acao", models.TextField(blank=True)),
                ("risco_residual", models.IntegerField(blank=True, null=True)),
                ("data_revisao", models.DateField(blank=True, null=True)),
                (
                    "ativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riscos",
                        to="nist.ativoinformacao",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação de Risco",
                "verbose_name_plural": "Avaliações de Risco",
            },
        ),
        migrations.CreateModel(
            name="BackupRegistro",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("completo", "Completo"),
                            ("incremental", "Incremental"),
                            ("diferencial", "Diferencial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_inicio", models.DateTimeField()),
                ("data_conclusao", models.DateTimeField(blank=True, null=True)),
                ("sucesso", models.BooleanField(default=False)),
                ("tamanho_bytes", models.BigIntegerField(blank=True, null=True)),
                ("localizacao", models.CharField(max_length=500)),
                ("verificado", models.BooleanField(default=False)),
                ("data_verificacao", models.DateTimeField(blank=True, null=True)),
                ("data_expiracao", models.DateField()),
                ("criptografado", models.BooleanField(default=True)),
                (
                    "algoritmo_criptografia",
                    models.CharField(default="AES-256", max_length=50),
                ),
                (
                    "ativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backups",
                        to="nist.ativoinformacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Backup",
                "verbose_name_plural": "Registros de Backup",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ControleAcesso",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("autenticacao", "Autenticação"),
                            ("autorizacao", "Autorização"),
                            ("segregacao", "Segregação de Funções"),
                            ("revisao_acesso", "Revisão de Acesso"),
                            ("gestao_privilegio", "Gestão de Privilégios"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descricao", models.TextField()),
                ("requisitos", models.JSONField(default=list)),
                ("implementacao", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejado", "Planejado"),
                            ("implementado", "Implementado"),
                            ("em_revisao", "Em Revisão"),
                            ("desativado", "Desativado"),
                        ],
                        default="implementado",
                        max_length=20,
                    ),
                ),
                ("ultima_verificacao", models.DateTimeField(blank=True, null=True)),
                (
                    "efetividade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("efetivo", "Efetivo"),
                            ("parcial", "Parcialmente Efetivo"),
                            ("inefetivo", "Inefetivo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controles_acesso",
                        to="nist.ativoinformacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Controle de Acesso",
                "verbose_name_plural": "Controles de Acesso",
            },
        ),
        migrations.CreateModel(
            name="PlanoRecuperacao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=200)),
                ("versao", models.CharField(max_length=20)),
                (
                    "rto",
                    models.IntegerField(help_text="Recovery Time Objective em horas"),
                ),
                (
                    "rpo",
                    models.IntegerField(help_text="Recovery Point Objective em horas"),
                ),
                ("procedimentos_recuperacao", models.TextField()),
                (
                    "ordem_recuperacao",
                    models.JSONField(
                        default=list, help_text="Ordem de prioridade para recuperação"
                    ),
                ),
                ("recursos_necessarios", models.JSONField(default=list)),
                ("site_contingencia", models.CharField(blank=True, max_length=200)),
                ("ultimo_teste", models.DateField(blank=True, null=True)),
                ("resultado_ultimo_teste", models.TextField(blank=True)),
                ("proximo_teste", models.DateField()),
                ("data_aprovacao", models.DateField(blank=True, null=True)),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sistemas_criticos",
                    models.ManyToManyField(
                        related_name="planos_recuperacao", to="nist.ativoinformacao"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Recuperação",
                "verbose_name_plural": "Planos de Recuperação",
            },
        ),
        migrations.CreateModel(
            name="PlanoRespostaIncidente",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=200)),
                ("versao", models.CharField(max_length=20)),
                (
                    "tipo_incidente",
                    models.CharField(
                        choices=[
                            ("malware", "Malware"),
                            ("phishing", "Phishing"),
                            ("vazamento", "Vazamento de Dados"),
                            ("ddos", "DDoS"),
                            ("acesso_nao_autorizado", "Acesso Não Autorizado"),
                            ("ransomware", "Ransomware"),
                            ("engenharia_social", "Engenharia Social"),
                            ("geral", "Geral"),
                        ],
                        max_length=50,
                    ),
                ),
                ("procedimento_preparacao", models.TextField()),
                ("procedimento_identificacao", models.TextField()),
                ("procedimento_contencao", models.TextField()),
                ("procedimento_erradicacao", models.TextField()),
                ("procedimento_recuperacao", models.TextField()),
                ("procedimento_licoes", models.TextField()),
                (
                    "equipe_resposta",
                    models.JSONField(
                        default=list, help_text="Membros da equipe e seus papéis"
                    ),
                ),
                ("contatos_emergencia", models.JSONField(default=list)),
                ("data_aprovacao", models.DateField(blank=True, null=True)),
                ("proxima_revisao", models.DateField()),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Resposta a Incidentes",
                "verbose_name_plural": "Planos de Resposta a Incidentes",
            },
        ),
        migrations.CreateModel(
            name="AlertaSeguranca",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "severidade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fonte", models.CharField(max_length=100)),
                ("dados_evento", models.JSONField(default=dict)),
                ("usuarios_afetados", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("novo", "Novo"),
                            ("triagem", "Em Triagem"),
                            ("investigacao", "Em Investigação"),
                            ("falso_positivo", "Falso Positivo"),
                            ("confirmado", "Confirmado"),
                            ("resolvido", "Resolvido"),
                        ],
                        default="novo",
                        max_length=20,
                    ),
                ),
                ("analise", models.TextField(blank=True)),
                ("data_resolucao", models.DateTimeField(blank=True, null=True)),
                (
                    "atribuido_para",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ativos_afetados",
                    models.ManyToManyField(blank=True, to="nist.ativoinformacao"),
                ),
                (
                    "regra",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas",
                        to="nist.regradeteccao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de Segurança",
                "verbose_name_plural": "Alertas de Segurança",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TesteRecuperacao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("tabletop", "Exercício de Mesa"),
                            ("walkthrough", "Walkthrough"),
                            ("simulacao", "Simulação"),
                            ("paralelo", "Teste Paralelo"),
                            ("completo", "Teste Completo"),
                        ],
                        max_length=30,
                    ),
                ),
                ("data_execucao", models.DateTimeField()),
                ("participantes", models.JSONField(default=list)),
                ("cenario", models.TextField()),
                (
                    "rto_alcancado",
                    models.IntegerField(
                        blank=True, help_text="RTO real em horas", null=True
                    ),
                ),
                (
                    "rpo_alcancado",
                    models.IntegerField(
                        blank=True, help_text="RPO real em horas", null=True
                    ),
                ),
                ("sucesso", models.BooleanField(default=False)),
                ("problemas_identificados", models.JSONField(default=list)),
                ("licoes_aprendidas", models.TextField(blank=True)),
                ("acoes_melhoria", models.JSONField(default=list)),
                (
                    "coordenado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testes",
                        to="nist.planorecuperacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teste de Recuperação",
                "verbose_name_plural": "Testes de Recuperação",
            },
        ),
    ]
