# Generated by Django 5.2.9 on 2025-12-13 03:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_head",
                        to="core.usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior"),
                            ("lead", "Lead/Oportunidade"),
                            ("manager", "Manager"),
                            ("director", "Director"),
                            ("executive", "Executive"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo/Designação",
                "verbose_name_plural": "Cargos/Designações",
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Código de ID do Funcionário",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("date_of_joining", models.DateField()),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nationality", models.CharField(max_length=100)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanente"),
                            ("contract", "Contrato"),
                            ("temporary", "Temporário"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("on_leave", "De Licença"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="hrm.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="hrm.designation",
                    ),
                ),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="hrm.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to="core.usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                (
                    "annual_entitlement",
                    models.IntegerField(
                        default=20, help_text="Dias de licença anual permitidos"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Licença",
                "verbose_name_plural": "Tipos de Licença",
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("submitted", "Submitted"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                            ("cancelled", "Cancelarado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approval_comments", models.TextField(blank=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to="core.usuário",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="hrm.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leaves",
                        to="hrm.leavetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licença/Férias",
                "verbose_name_plural": "Licenças/Férias",
            },
        ),
        migrations.CreateModel(
            name="PerformanceGoal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("target_value", models.CharField(max_length=255)),
                ("achieved_value", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Nãot Started"),
                            ("in_progress", "Em Progresso"),
                            ("completed", "Concluído"),
                            ("on_track", "On Track"),
                            ("at_risk", "At Risk"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("progress_percentage", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="hrm.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta de Desempenho",
                "verbose_name_plural": "Metas de Desempenho",
            },
        ),
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("review_period_start", models.DateField()),
                ("review_period_end", models.DateField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                ("comments", models.TextField()),
                ("strengths", models.TextField(blank=True)),
                ("areas_for_improvement", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("submitted", "Submitted"),
                            ("approved", "Aprovado"),
                            ("completed", "Concluído"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to="hrm.employee",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_reviews_given",
                        to="core.usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação de Desempenho",
                "verbose_name_plural": "Avaliações de Desempenho",
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "is_template",
                    models.BooleanField(
                        default=True,
                        help_text="Se Verdadeiro, pode ser usado como modelo para vários funcionários",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estrutura Salarial",
                "verbose_name_plural": "Estruturas Salariais",
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeSalary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("effective_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary",
                        to="hrm.employee",
                    ),
                ),
                (
                    "salary_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="hrm.salarystructure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salário do Funcionário",
                "verbose_name_plural": "Salários dos Funcionários",
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("description", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno",
                "verbose_name_plural": "Turnos",
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "month",
                    models.DateField(help_text="Mês do contracheque (primeiro dia)"),
                ),
                ("salary_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("approved", "Aprovado"),
                            ("paid", "Pago"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="hrm.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contracheque",
                "verbose_name_plural": "Contracheques",
                "unique_together": {("company", "employee", "month")},
            },
        ),
        migrations.CreateModel(
            name="Presença",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField()),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("half_day", "Half Day"),
                            ("late", "Late"),
                            ("on_leave", "De Licença"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Horas trabalhadas além do horário de turno",
                        max_digits=5,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="hrm.employee",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance",
                        to="hrm.shift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frequência",
                "verbose_name_plural": "Presença Records",
                "unique_together": {("company", "employee", "date")},
            },
        ),
    ]
