# Generated by Django 5.2.9 on 2025-12-13 02:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_company_subscription_plan_remove_user_company_and_more"),
        ("hrm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
            },
        ),
        migrations.AlterModelOptions(
            name="designation",
            options={
                "verbose_name": "Cargo/Designação",
                "verbose_name_plural": "Cargos/Designações",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
            },
        ),
        migrations.AlterModelOptions(
            name="employeesalary",
            options={
                "verbose_name": "Salário do Funcionário",
                "verbose_name_plural": "Salários dos Funcionários",
            },
        ),
        migrations.AlterModelOptions(
            name="leave",
            options={
                "verbose_name": "Licença/Férias",
                "verbose_name_plural": "Licenças/Férias",
            },
        ),
        migrations.AlterModelOptions(
            name="leavetype",
            options={
                "verbose_name": "Tipo de Licença",
                "verbose_name_plural": "Tipos de Licença",
            },
        ),
        migrations.AlterModelOptions(
            name="payslip",
            options={
                "verbose_name": "Contracheque",
                "verbose_name_plural": "Contracheques",
            },
        ),
        migrations.AlterModelOptions(
            name="performancegoal",
            options={
                "verbose_name": "Meta de Desempenho",
                "verbose_name_plural": "Metas de Desempenho",
            },
        ),
        migrations.AlterModelOptions(
            name="performancereview",
            options={
                "verbose_name": "Avaliação de Desempenho",
                "verbose_name_plural": "Avaliações de Desempenho",
            },
        ),
        migrations.AlterModelOptions(
            name="salarystructure",
            options={
                "verbose_name": "Estrutura Salarial",
                "verbose_name_plural": "Estruturas Salariais",
            },
        ),
        migrations.AlterModelOptions(
            name="shift",
            options={"verbose_name": "Turno", "verbose_name_plural": "Turnos"},
        ),
        migrations.AlterField(
            model_name="department",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="department_head",
                to="core.usuário",
            ),
        ),
        migrations.AlterField(
            model_name="designation",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="designation",
            name="level",
            field=models.CharField(
                choices=[
                    ("entry", "Entry Level"),
                    ("mid", "Mid Level"),
                    ("senior", "Senior"),
                    ("lead", "Lead/Oportunidade"),
                    ("manager", "Manager"),
                    ("director", "Director"),
                    ("executive", "Executive"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(
                help_text="Código de ID do Funcionário", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("permanent", "Permanente"),
                    ("contract", "Contrato"),
                    ("temporary", "Temporário"),
                    ("internship", "Internship"),
                    ("freelance", "Freelance"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativo"),
                    ("on_leave", "De Licença"),
                    ("suspended", "Suspended"),
                    ("terminated", "Terminated"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to="core.usuário",
            ),
        ),
        migrations.AlterField(
            model_name="employeesalary",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to="core.usuário",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("submitted", "Submitted"),
                    ("approved", "Aprovado"),
                    ("rejected", "Rejeitado"),
                    ("cancelled", "Cancelarado"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="annual_entitlement",
            field=models.IntegerField(
                default=20, help_text="Dias de licença anual permitidos"
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="month",
            field=models.DateField(help_text="Mês do contracheque (primeiro dia)"),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("approved", "Aprovado"),
                    ("paid", "Pago"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="performancegoal",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="performancegoal",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Nãot Started"),
                    ("in_progress", "Em Progresso"),
                    ("completed", "Concluído"),
                    ("on_track", "On Track"),
                    ("at_risk", "At Risk"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="performancereview",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="performancereview",
            name="reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performance_reviews_given",
                to="core.usuário",
            ),
        ),
        migrations.AlterField(
            model_name="performancereview",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("submitted", "Submitted"),
                    ("approved", "Aprovado"),
                    ("completed", "Concluído"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salarystructure",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="salarystructure",
            name="is_template",
            field=models.BooleanField(
                default=True,
                help_text="Se Verdadeiro, pode ser usado como modelo para vários funcionários",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.CreateModel(
            name="Presença",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField()),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("half_day", "Half Day"),
                            ("late", "Late"),
                            ("on_leave", "De Licença"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Horas trabalhadas além do horário de turno",
                        max_digits=5,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="hrm.employee",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance",
                        to="hrm.shift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frequência",
                "verbose_name_plural": "Presença Records",
                "unique_together": {("company", "employee", "date")},
            },
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
    ]
