# Generated by Django 5.1.3 on 2025-12-02 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('retention_days', models.IntegerField(default=365)),
                ('log_login_attempts', models.BooleanField(default=True)),
                ('log_data_changes', models.BooleanField(default=True)),
                ('log_exports', models.BooleanField(default=True)),
                ('require_2fa', models.BooleanField(default=False)),
                ('password_expiry_days', models.IntegerField(blank=True, null=True)),
                ('max_failed_login_attempts', models.IntegerField(default=5)),
                ('lockout_duration_minutes', models.IntegerField(default=15)),
                ('company', models.ForeignKey(help_text='Company (Tenant) this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='core.company')),
            ],
            options={
                'verbose_name': 'Audit Config',
                'verbose_name_plural': 'Audit Configs',
            },
        ),
        migrations.CreateModel(
            name='IpBlocklist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('suspicious_activity', 'Suspicious Activity'), ('manual_block', 'Manual Block'), ('phishing', 'Phishing Attempt')], max_length=50)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(help_text='Company (Tenant) this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='core.company')),
            ],
            options={
                'verbose_name': 'IP Blocklist',
                'verbose_name_plural': 'IP Blocklists',
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(choices=[('login_success', 'Successful Login'), ('login_failed', 'Failed Login'), ('password_changed', 'Password Changed'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('data_export', 'Data Export'), ('data_import', 'Data Import'), ('brute_force_attempt', 'Brute Force Attempt'), ('suspicious_activity', 'Suspicious Activity'), ('phishing_attempt', 'Phishing Attempt'), ('unauthorized_access', 'Unauthorized Access Attempt')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('company', models.ForeignKey(help_text='Company (Tenant) this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='core.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('authenticator', 'Authenticator App')], default='email', max_length=50)),
                ('backup_codes', models.JSONField(blank=True, default=list)),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(help_text='Company (Tenant) this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two Factor Auth',
                'verbose_name_plural': 'Two Factor Auths',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(max_length=500)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('other', 'Other')], default='desktop', max_length=20)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(help_text='Company (Tenant) this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
            },
        ),
    ]
