# Generated by Django 5.2.9 on 2025-12-13 02:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_company_subscription_plan_remove_user_company_and_more"),
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersession",
            name="company",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="ipblocklist",
            options={
                "verbose_name": "Lista Bloqueada de IP",
                "verbose_name_plural": "Listas Bloqueadas de IP",
            },
        ),
        migrations.AlterModelOptions(
            name="securityevent",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Evento de Segurança",
                "verbose_name_plural": "Eventos de Segurança",
            },
        ),
        migrations.AlterModelOptions(
            name="twofactorauth",
            options={
                "verbose_name": "Autenticação de Dois Fatores",
                "verbose_name_plural": "Autenticações de Dois Fatores",
            },
        ),
        migrations.AlterField(
            model_name="ipblocklist",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_success", "Sucessoful Entrar"),
                    ("login_failed", "Failed Entrar"),
                    ("password_changed", "Senha Alterard"),
                    ("permission_granted", "Permission Granted"),
                    ("permission_revoked", "Permission Revoked"),
                    ("data_export", "Data Exportar"),
                    ("data_import", "Data Importar"),
                    ("brute_force_attempt", "Brute Force Attempt"),
                    ("suspicious_activity", "Suspicious Activity"),
                    ("phishing_attempt", "Phishing Attempt"),
                    ("unauthorized_access", "Unauthorized Access Attempt"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Baixo"),
                    ("medium", "Médio"),
                    ("high", "Alto"),
                    ("critical", "Crítico"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_events",
                to="core.usuário",
            ),
        ),
        migrations.AlterField(
            model_name="twofactorauth",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="twofactorauth",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="two_factor_auth",
                to="core.usuário",
            ),
        ),
        migrations.CreateModel(
            name="AuditoriaConfig",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("retention_days", models.IntegerField(default=365)),
                ("log_login_attempts", models.BooleanField(default=True)),
                ("log_data_changes", models.BooleanField(default=True)),
                ("log_exports", models.BooleanField(default=True)),
                ("require_2fa", models.BooleanField(default=False)),
                ("password_expiry_days", models.IntegerField(blank=True, null=True)),
                ("max_failed_login_attempts", models.IntegerField(default=5)),
                ("lockout_duration_minutes", models.IntegerField(default=15)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Auditoriaoria",
                "verbose_name_plural": "Configurações de Auditoriaoria",
            },
        ),
        migrations.CreateModel(
            name="UsuárioSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("token", models.CharField(max_length=500)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("other", "Other"),
                        ],
                        default="desktop",
                        max_length=20,
                    ),
                ),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="core.usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão do Usuário",
                "verbose_name_plural": "Sessões do Usuário",
            },
        ),
        migrations.DeleteModel(
            name="AuditConfig",
        ),
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
