# Generated by Django 5.2.9 on 2025-12-13 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_company_subscription_plan_remove_user_company_and_more"),
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={"verbose_name": "Candidato", "verbose_name_plural": "Candidatos"},
        ),
        migrations.AlterModelOptions(
            name="interviewschedule",
            options={
                "verbose_name": "Agendamento de Entrevista",
                "verbose_name_plural": "Agendamentos de Entrevista",
            },
        ),
        migrations.AlterModelOptions(
            name="job",
            options={
                "verbose_name": "Vaga/Emprego",
                "verbose_name_plural": "Vagas/Empregos",
            },
        ),
        migrations.AlterModelOptions(
            name="jobapplication",
            options={
                "verbose_name": "Candidatura/Solicitação de Emprego",
                "verbose_name_plural": "Candidaturas/Solicitações de Emprego",
            },
        ),
        migrations.AlterModelOptions(
            name="offerletter",
            options={
                "verbose_name": "Carta de Oferta",
                "verbose_name_plural": "Cartas de Oferta",
            },
        ),
        migrations.AlterField(
            model_name="candidate",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="skills",
            field=models.TextField(
                blank=True, help_text="Habilidades separadas por vírgulas"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativo"),
                    ("interested", "Interested"),
                    ("not_interested", "Nãot Interested"),
                    ("hired", "Contratado"),
                    ("archived", "Arquivado"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="interviewschedule",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="interviewschedule",
            name="interview_type",
            field=models.CharField(
                choices=[
                    ("phone", "Telefone"),
                    ("video", "Vídeo"),
                    ("in_person", "In Person"),
                    ("group", "Group"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="interviewschedule",
            name="interviewers",
            field=models.ManyToManyField(
                related_name="interview_schedules", to="core.usuário"
            ),
        ),
        migrations.AlterField(
            model_name="interviewschedule",
            name="meeting_link",
            field=models.URLField(blank=True, help_text="Link do Zoom/Google Meet"),
        ),
        migrations.AlterField(
            model_name="interviewschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Concluído"),
                    ("cancelled", "Cancelarado"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contrato"),
                    ("internship", "Internship"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="experience_required",
            field=models.IntegerField(default=0, help_text="Anos de experiência"),
        ),
        migrations.AlterField(
            model_name="job",
            name="hiring_manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs_managing",
                to="core.usuário",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("published", "Publicado"),
                    ("closed", "Fechado"),
                    ("on_hold", "Em Espera"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="rating",
            field=models.IntegerField(
                blank=True, help_text="Classificação de 1-5 estrelas", null=True
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("screening", "Triagem"),
                    ("interview", "Entrevista"),
                    ("offered", "Offered"),
                    ("hired", "Contratado"),
                    ("rejected", "Rejeitado"),
                    ("withdrew", "Withdrew"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="offerletter",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="offerletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("sent", "Enviado"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejeitado"),
                    ("expired", "Expirado"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
