# Generated by Django 5.1.3 on 2025-12-12 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_auditlog_options_alter_company_options_and_more"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estimate",
            options={"verbose_name": "Orçamento", "verbose_name_plural": "Orçamentos"},
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={"verbose_name": "Despesa", "verbose_name_plural": "Despesas"},
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={"verbose_name": "Fatura", "verbose_name_plural": "Faturas"},
        ),
        migrations.AlterModelOptions(
            name="invoiceitem",
            options={
                "verbose_name": "Item da Fatura",
                "verbose_name_plural": "Itens da Fatura",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Pagamento", "verbose_name_plural": "Pagamentos"},
        ),
        migrations.AlterModelOptions(
            name="paymentgateway",
            options={
                "verbose_name": "Gateway de Pagamento",
                "verbose_name_plural": "Gateways de Pagamento",
            },
        ),
        migrations.AlterModelOptions(
            name="proposal",
            options={"verbose_name": "Proposta", "verbose_name_plural": "Propostas"},
        ),
        migrations.AlterField(
            model_name="estimate",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("sent", "Enviado"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejeitado"),
                    ("expired", "Expirado"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("submitted", "Submitted"),
                    ("approved", "Aprovado"),
                    ("reimbursed", "Reimbursed"),
                    ("rejected", "Rejeitado"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("sent", "Enviado"),
                    ("viewed", "Viewed"),
                    ("partially_paid", "Partially Paid"),
                    ("paid", "Pago"),
                    ("overdue", "Vencido"),
                    ("cancelled", "Cancelado"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("processing", "Processing"),
                    ("completed", "Concluído"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelarado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymentgateway",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("sent", "Enviado"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejeitado"),
                    ("expired", "Expirado"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
