# Generated by Django 5.1.3 on 2025-12-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_estimate_options_alter_expense_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("travel", "Viagem"),
                    ("meals", "Alimentação"),
                    ("supplies", "Suprimentos"),
                    ("software", "Software"),
                    ("other", "Outros"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("submitted", "Submetido"),
                    ("approved", "Aprovado"),
                    ("reimbursed", "Reembolsado"),
                    ("rejected", "Rejeitado"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Cartão de Crédito"),
                    ("debit_card", "Cartão de Débito"),
                    ("bank_transfer", "Transferência Bancária"),
                    ("check", "Cheque"),
                    ("cash", "Dinheiro"),
                    ("other", "Outros"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("processing", "Processando"),
                    ("completed", "Concluído"),
                    ("failed", "Falhou"),
                    ("cancelled", "Cancelarado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
