# Generated by Django 5.2.9 on 2025-12-13 03:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("access", "Controle de Acesso"),
                            ("authentication", "Autenticação"),
                            ("data", "Proteção de Dados"),
                            ("network", "Rede"),
                            ("device", "Dispositivo"),
                            ("time", "Temporal"),
                            ("location", "Geolocalização"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "applies_to_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Roles afetadas (vazio = todas)",
                    ),
                ),
                (
                    "applies_to_resources",
                    models.JSONField(
                        blank=True, default=list, help_text="Padrões de URL (regex)"
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict, help_text="Condições para ativação da política"
                    ),
                ),
                (
                    "action_on_match",
                    models.CharField(
                        choices=[
                            ("allow", "Permitir"),
                            ("deny", "Negar"),
                            ("challenge", "Solicitar MFA"),
                            ("log", "Apenas Registrar"),
                            ("alert", "Alertar Admin"),
                        ],
                        default="allow",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_enforced", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Política de Segurança",
                "verbose_name_plural": "Políticas de Segurança",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="APISecurityToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("access", "Access Token"),
                            ("refresh", "Refresh Token"),
                            ("api_key", "API Key"),
                            ("service", "Service Account"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("token_prefix", models.CharField(max_length=10)),
                (
                    "scopes",
                    models.JSONField(
                        default=list,
                        help_text="Escopos permitidos: read:users, write:employees, etc",
                    ),
                ),
                (
                    "allowed_ips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IPs permitidos (vazio = todos)",
                    ),
                ),
                (
                    "allowed_resources",
                    models.JSONField(
                        blank=True, default=list, help_text="Padrões de URL permitidos"
                    ),
                ),
                ("rate_limit_per_minute", models.IntegerField(default=60)),
                ("rate_limit_per_day", models.IntegerField(default=10000)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("total_requests", models.IntegerField(default=0)),
                ("is_revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_reason", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de API",
                "verbose_name_plural": "Tokens de API",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreatIndicator",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "indicator_type",
                    models.CharField(
                        choices=[
                            ("ip", "Endereço IP"),
                            ("domain", "Domínio"),
                            ("email", "Email"),
                            ("hash", "File Hash"),
                            ("user_agent", "User Agent"),
                            ("pattern", "Padrão de Ataque"),
                        ],
                        max_length=20,
                    ),
                ),
                ("indicator_value", models.CharField(db_index=True, max_length=500)),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("info", "Informativo"),
                            ("low", "Baixo"),
                            ("medium", "Médio"),
                            ("high", "Alto"),
                            ("critical", "Crítico"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("source", models.CharField(max_length=100)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("times_observed", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Indicador de Ameaça",
                "verbose_name_plural": "Indicadores de Ameaça",
                "indexes": [
                    models.Index(
                        fields=["indicator_type", "indicator_value"],
                        name="zero_trust__indicat_f1a38c_idx",
                    ),
                    models.Index(
                        fields=["threat_level", "is_active"],
                        name="zero_trust__threat__ca96ce_idx",
                    ),
                ],
                "unique_together": {("indicator_type", "indicator_value")},
            },
        ),
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("device_fingerprint", models.CharField(db_index=True, max_length=512)),
                ("device_name", models.CharField(blank=True, max_length=100)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop/Laptop"),
                            ("mobile", "Smartphone"),
                            ("tablet", "Tablet"),
                            ("terminal", "Terminal/Kiosk"),
                            ("api_client", "API Client"),
                        ],
                        default="desktop",
                        max_length=20,
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("browser_name", models.CharField(blank=True, max_length=50)),
                ("browser_version", models.CharField(blank=True, max_length=20)),
                ("os_name", models.CharField(blank=True, max_length=50)),
                ("os_version", models.CharField(blank=True, max_length=20)),
                ("screen_resolution", models.CharField(blank=True, max_length=20)),
                (
                    "trust_level",
                    models.CharField(
                        choices=[
                            ("untrusted", "Não Confiável"),
                            ("limited", "Confiança Limitada"),
                            ("standard", "Confiança Padrão"),
                            ("elevated", "Confiança Elevada"),
                            ("corporate", "Dispositivo Corporativo"),
                        ],
                        default="untrusted",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_blocked", models.BooleanField(default=False)),
                ("blocked_reason", models.TextField(blank=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_location", models.CharField(blank=True, max_length=100)),
                ("is_pwa_installed", models.BooleanField(default=False)),
                ("push_subscription", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo Confiável",
                "verbose_name_plural": "Dispositivos Confiáveis",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="ContinuousAuth",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_key", models.CharField(max_length=255, unique=True)),
                ("session_started", models.DateTimeField(auto_now_add=True)),
                ("session_expires", models.DateTimeField()),
                ("confidence_score", models.IntegerField(default=100)),
                ("min_confidence_threshold", models.IntegerField(default=70)),
                ("last_verification", models.DateTimeField(auto_now_add=True)),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("password", "Senha"),
                            ("mfa_totp", "MFA - TOTP"),
                            ("mfa_sms", "MFA - SMS"),
                            ("mfa_email", "MFA - Email"),
                            ("biometric", "Biometria"),
                            ("passkey", "Passkey/WebAuthn"),
                            ("behavioral", "Análise Comportamental"),
                            ("device_trust", "Confiança do Dispositivo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("next_verification_due", models.DateTimeField()),
                ("auth_factors_used", models.JSONField(blank=True, default=list)),
                ("auth_level", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_reauthentication", models.BooleanField(default=False)),
                (
                    "reauthentication_reason",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="continuous_auths",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="continuous_auths",
                        to="zero_trust.trusteddevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autenticação Contínua",
                "verbose_name_plural": "Autenticações Contínuas",
            },
        ),
        migrations.CreateModel(
            name="AccessContext",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                ("request_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("ip_type", models.CharField(blank=True, max_length=20)),
                ("geo_country", models.CharField(blank=True, max_length=2)),
                ("geo_city", models.CharField(blank=True, max_length=100)),
                ("geo_coordinates", models.CharField(blank=True, max_length=50)),
                ("asn", models.CharField(blank=True, max_length=50)),
                ("isp", models.CharField(blank=True, max_length=100)),
                ("access_time", models.DateTimeField(auto_now_add=True)),
                ("is_business_hours", models.BooleanField(default=True)),
                ("is_unusual_time", models.BooleanField(default=False)),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_path", models.CharField(max_length=500)),
                ("resource_method", models.CharField(max_length=10)),
                (
                    "resource_sensitivity",
                    models.CharField(default="normal", max_length=20),
                ),
                ("risk_score", models.IntegerField(default=0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Baixo"),
                            ("medium", "Médio"),
                            ("high", "Alto"),
                            ("critical", "Crítico"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("risk_factors", models.JSONField(default=list)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("allow", "Permitido"),
                            ("deny", "Negado"),
                            ("challenge", "Desafio MFA"),
                            ("step_up", "Step-Up Auth"),
                            ("block", "Bloqueado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("decision_reason", models.TextField(blank=True)),
                ("policy_applied", models.CharField(blank=True, max_length=100)),
                ("was_successful", models.BooleanField(default=True)),
                ("response_code", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_contexts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_contexts",
                        to="zero_trust.trusteddevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contexto de Acesso",
                "verbose_name_plural": "Contextos de Acesso",
                "ordering": ["-access_time"],
            },
        ),
        migrations.CreateModel(
            name="UserBehaviorProfile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "typical_login_hours",
                    models.JSONField(
                        default=dict,
                        help_text="Distribuição de horários de login por dia da semana",
                    ),
                ),
                (
                    "typical_session_duration",
                    models.DurationField(blank=True, null=True),
                ),
                ("typical_locations", models.JSONField(blank=True, default=list)),
                ("typical_ips", models.JSONField(blank=True, default=list)),
                ("known_devices_count", models.IntegerField(default=0)),
                ("primary_device_type", models.CharField(blank=True, max_length=20)),
                ("typical_resources", models.JSONField(blank=True, default=list)),
                ("typical_actions_per_session", models.IntegerField(default=0)),
                ("baseline_risk_score", models.IntegerField(default=20)),
                ("anomaly_count_30d", models.IntegerField(default=0)),
                ("last_anomaly_detected", models.DateTimeField(blank=True, null=True)),
                (
                    "profile_maturity",
                    models.CharField(
                        choices=[
                            ("learning", "Aprendendo"),
                            ("baseline", "Baseline Estabelecido"),
                            ("mature", "Perfil Maduro"),
                        ],
                        default="learning",
                        max_length=20,
                    ),
                ),
                ("data_points_collected", models.IntegerField(default=0)),
                ("last_profile_update", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil Comportamental",
                "verbose_name_plural": "Perfis Comportamentais",
            },
        ),
        migrations.AddIndex(
            model_name="trusteddevice",
            index=models.Index(
                fields=["user", "is_active"], name="zero_trust__user_id_4c7754_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trusteddevice",
            index=models.Index(
                fields=["device_fingerprint"], name="zero_trust__device__eac3b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trusteddevice",
            index=models.Index(
                fields=["trust_level", "is_verified"],
                name="zero_trust__trust_l_ad8f3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="continuousauth",
            index=models.Index(
                fields=["user", "is_active"], name="zero_trust__user_id_e350e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="continuousauth",
            index=models.Index(
                fields=["session_key"], name="zero_trust__session_3cf09e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="continuousauth",
            index=models.Index(
                fields=["confidence_score"], name="zero_trust__confide_65bea4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesscontext",
            index=models.Index(
                fields=["user", "-access_time"], name="zero_trust__user_id_67cc08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesscontext",
            index=models.Index(
                fields=["ip_address", "-access_time"],
                name="zero_trust__ip_addr_2beb76_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accesscontext",
            index=models.Index(
                fields=["risk_level", "-access_time"],
                name="zero_trust__risk_le_f98aec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accesscontext",
            index=models.Index(
                fields=["decision", "-access_time"],
                name="zero_trust__decisio_474275_idx",
            ),
        ),
    ]
