# Generated by Django 5.2.9 on 2025-12-13 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensal"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Anual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        blank=True,
                        help_text="Máximo de usuários por empresa, nulo=ilimitado",
                        null=True,
                    ),
                ),
                (
                    "max_storage_gb",
                    models.IntegerField(
                        blank=True,
                        help_text="Armazenamento máximo em GB, nulo=ilimitado",
                        null=True,
                    ),
                ),
                ("includes_hrm", models.BooleanField(default=False)),
                ("includes_finance", models.BooleanField(default=False)),
                ("includes_crm", models.BooleanField(default=False)),
                ("includes_recruitment", models.BooleanField(default=False)),
                ("includes_projects", models.BooleanField(default=False)),
                ("includes_assets", models.BooleanField(default=False)),
                (
                    "support_level",
                    models.CharField(
                        choices=[
                            ("email", "Email Support"),
                            ("priority", "Priority Support"),
                            ("dedicated", "Dedicated Support"),
                        ],
                        default="email",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Plano de Assinatura",
                "verbose_name_plural": "Planos de Assinatura",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("renewal_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="BRL", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Teste"),
                            ("active", "Ativo"),
                            ("paused", "Pausado"),
                            ("cancelled", "Cancelarado"),
                            ("expired", "Expirado"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("auto_renew", models.BooleanField(default=True)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("razorpay", "Razorpay"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "gateway_subscription_id",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="saas_admin.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura",
                "verbose_name_plural": "Assinaturas",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed Amount"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                (
                    "max_usage",
                    models.IntegerField(
                        blank=True,
                        help_text="Número máximo de vezes que o cupom pode ser usado",
                        null=True,
                    ),
                ),
                ("times_used", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "applicable_plans",
                    models.ManyToManyField(
                        blank=True,
                        related_name="coupons",
                        to="saas_admin.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cupom",
                "verbose_name_plural": "Cupons",
            },
        ),
        migrations.CreateModel(
            name="BillingInvoice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="BRL", max_length=3)),
                ("issued_date", models.DateField()),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("sent", "Enviado"),
                            ("paid", "Pago"),
                            ("overdue", "Vencido"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("transaction_id", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_invoices",
                        to="saas_admin.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura de Cobrança",
                "verbose_name_plural": "Faturas de Cobrança",
                "unique_together": {("company", "invoice_number")},
            },
        ),
    ]
