# Generated by Django 5.2.9 on 2025-12-13 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_company_subscription_plan_remove_user_company_and_more"),
        ("saas_admin", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billinginvoice",
            options={
                "verbose_name": "Fatura de Cobrança",
                "verbose_name_plural": "Faturas de Cobrança",
            },
        ),
        migrations.AlterModelOptions(
            name="coupon",
            options={"verbose_name": "Cupom", "verbose_name_plural": "Cupons"},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "verbose_name": "Assinatura",
                "verbose_name_plural": "Assinaturas",
            },
        ),
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={
                "ordering": ["display_order"],
                "verbose_name": "Plano de Assinatura",
                "verbose_name_plural": "Planos de Assinatura",
            },
        ),
        migrations.AlterField(
            model_name="billinginvoice",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="billinginvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("sent", "Enviado"),
                    ("paid", "Pago"),
                    ("overdue", "Vencido"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="max_usage",
            field=models.IntegerField(
                blank=True,
                help_text="Número máximo de vezes que o cupom pode ser usado",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("trial", "Teste"),
                    ("active", "Ativo"),
                    ("paused", "Pausado"),
                    ("cancelled", "Cancelarado"),
                    ("expired", "Expirado"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("monthly", "Mensal"),
                    ("quarterly", "Quarterly"),
                    ("annual", "Anual"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_storage_gb",
            field=models.IntegerField(
                blank=True,
                help_text="Armazenamento máximo em GB, nulo=ilimitado",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_users",
            field=models.IntegerField(
                blank=True,
                help_text="Máximo de usuários por empresa, nulo=ilimitado",
                null=True,
            ),
        ),
    ]
