# Generated by Django 5.2.9 on 2025-12-13 13:40

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
        ("saas_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="saas_admin.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="auditorialog",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AddField(
            model_name="empresadomain",
            name="company",
            field=models.ForeignKey(
                help_text="A empresa a qual este domínio pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="core.empresa",
            ),
        ),
        migrations.AddField(
            model_name="usuário",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a qual este usuário pertence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="core.empresa",
            ),
        ),
        migrations.AddField(
            model_name="usuário",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="usuário",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="auditorialog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="core.usuário",
            ),
        ),
        migrations.AddField(
            model_name="usuáriopermission",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AddField(
            model_name="usuáriopermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_permissions",
                to="core.usuário",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="empresadomain",
            unique_together={("company", "is_primary")},
        ),
        migrations.AlterUniqueTogether(
            name="usuário",
            unique_together={("email", "company")},
        ),
        migrations.AddIndex(
            model_name="auditorialog",
            index=models.Index(
                fields=["company", "-created_at"], name="core_audito_company_d749ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditorialog",
            index=models.Index(
                fields=["user", "-created_at"], name="core_audito_user_id_3e6884_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditorialog",
            index=models.Index(fields=["action"], name="core_audito_action_0665c5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="usuáriopermission",
            unique_together={("company", "user", "module")},
        ),
    ]
