# Generated by Django 5.1.3 on 2025-12-03 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('saas_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='saas_admin.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(help_text='Company (Tenant) this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='core.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company'),
        ),
        migrations.AddField(
            model_name='companydomain',
            name='company',
            field=models.ForeignKey(help_text='The company this domain belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.company'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='company',
            field=models.ForeignKey(help_text='Company (Tenant) this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='core.company'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', '-created_at'], name='core_auditl_company_05a872_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='core_auditl_user_id_969660_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='companydomain',
            unique_together={('company', 'is_primary')},
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('company', 'user', 'module')},
        ),
    ]
