# Generated by Django 5.1.3 on 2025-12-12 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
            },
        ),
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.AlterModelOptions(
            name="companydomain",
            options={
                "verbose_name": "Domínio da Empresa",
                "verbose_name_plural": "Domínios da Empresa",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
        migrations.AlterModelOptions(
            name="userpermission",
            options={
                "verbose_name": "Permissão do Usuário",
                "verbose_name_plural": "Permissões do Usuário",
            },
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Criar"),
                    ("update", "Atualizar"),
                    ("delete", "Excluir"),
                    ("login", "Entrar"),
                    ("logout", "Sair"),
                    ("export", "Exportar"),
                    ("import", "Importar"),
                    ("download", "Baixar"),
                    ("permission_change", "Mudança de Permissão"),
                    ("config_change", "Mudança de Configuração"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-10", "1-10 funcionários"),
                    ("11-50", "11-50 funcionários"),
                    ("51-200", "51-200 funcionários"),
                    ("201-500", "201-500 funcionários"),
                    ("500+", "500+ funcionários"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="currency",
            field=models.CharField(
                default="BRL",
                help_text="Código de moeda padrão (ISO 4217)",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, help_text="Descrição da Empresa"),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(
                help_text="E-mail principal da empresa", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="industry",
            field=models.CharField(
                blank=True,
                help_text="Vertical da indústria (ex: Tecnologia, Saúde, Finanças)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo da empresa",
                null=True,
                upload_to="company_logos/",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                help_text="Nome da Empresa", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(
                help_text="Identificador único para URL (ex: acme-corp)", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("trial", "Teste"),
                    ("active", "Ativo"),
                    ("paused", "Pausado"),
                    ("cancelled", "Cancelado"),
                    ("expired", "Expirado"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="timezone",
            field=models.CharField(
                default="America/Sao_Paulo",
                help_text="Fuso horário da empresa",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="companydomain",
            name="company",
            field=models.ForeignKey(
                help_text="A empresa a qual este domínio pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="companydomain",
            name="domain",
            field=models.CharField(
                help_text="Nome de domínio (ex: tenant.example.com)",
                max_length=253,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="companydomain",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="Este é o domínio primário da empresa?"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a qual este usuário pertence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="module",
            field=models.CharField(
                choices=[
                    ("employees", "Funcionários"),
                    ("leaves", "Licenças/Férias"),
                    ("attendance", "Frequência"),
                    ("payroll", "Folha de Pagamento"),
                    ("performance", "Desempenho"),
                    ("projects", "Projetos"),
                    ("tasks", "Tarefas"),
                    ("timelogs", "Registros de Tempo"),
                    ("finance", "Finanças"),
                    ("crm", "CRM"),
                    ("recruitment", "Recrutamento"),
                    ("assets", "Ativos/Bens"),
                    ("tickets", "Tickets/Chamados"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="permission_level",
            field=models.CharField(
                choices=[
                    ("view", "Visualizar"),
                    ("create", "Criar"),
                    ("edit", "Editar"),
                    ("delete", "Excluir"),
                    ("export", "Exportar"),
                ],
                max_length=20,
            ),
        ),
    ]
