# Generated by Django 5.2.9 on 2025-12-13 02:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0002_initial"),
        ("saas_admin", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="subscription_plan",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company",
        ),
        migrations.RemoveField(
            model_name="companydomain",
            name="company",
        ),
        migrations.RemoveField(
            model_name="userpermission",
            name="company",
        ),
        migrations.AlterUniqueTogether(
            name="companydomain",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="userpermission",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="userpermission",
            unique_together=None,
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nãome da Empresa", max_length=255, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador único para URL (ex: acme-corp)",
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descrição da Empresa"),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="E-mail principal da empresa", max_length=254
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        help_text="Vertical da indústria (ex: Tecnologia, Saúde, Finanças)",
                        max_length=100,
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-10", "1-10 employees"),
                            ("11-50", "11-50 employees"),
                            ("51-200", "51-200 employees"),
                            ("201-500", "201-500 employees"),
                            ("500+", "500+ employees"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="BRL",
                        help_text="Código de moeda padrão (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/Sao_Paulo",
                        help_text="Fuso horário da empresa",
                        max_length=50,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo da empresa",
                        null=True,
                        upload_to="company_logos/",
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("trial", "Teste"),
                            ("active", "Ativo"),
                            ("paused", "Pausado"),
                            ("cancelled", "Cancelarado"),
                            ("expired", "Expirado"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("subscription_ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_on_trial", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to="saas_admin.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmpresaDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Nãome de domínio (ex: tenant.example.com)",
                        max_length=253,
                        unique=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Este é o domínio primário da empresa?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="A empresa a qual este domínio pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa Domain",
                "verbose_name_plural": "Domínios da Empresa",
            },
        ),
        migrations.CreateModel(
            name="Usuário",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="user_avatars/"),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("is_verified", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("two_factor_enabled", models.BooleanField(default=False)),
                ("is_employee", models.BooleanField(default=False)),
                ("is_contractor", models.BooleanField(default=False)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("pt-br", "Português (Brasil)"),
                            ("en", "English"),
                            ("es", "Español"),
                        ],
                        default="pt-br",
                        max_length=10,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(default="America/Sao_Paulo", max_length=50),
                ),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("login_count", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a qual este usuário pertence",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="core.empresa",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditoriaLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Deletar"),
                            ("login", "Entrar"),
                            ("logout", "Sair"),
                            ("export", "Exportar"),
                            ("import", "Importar"),
                            ("download", "Download"),
                            ("permission_change", "Mudança de Permissão"),
                            ("config_change", "Configuração Alterar"),
                        ],
                        max_length=50,
                    ),
                ),
                ("module", models.CharField(max_length=50)),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=255)),
                ("changes", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="core.usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoria Log",
                "verbose_name_plural": "Logs de Auditoriaoria",
            },
        ),
        migrations.CreateModel(
            name="UsuárioPermission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("employees", "Funcionários"),
                            ("leaves", "Licenças/Férias"),
                            ("attendance", "Frequência"),
                            ("payroll", "Payroll"),
                            ("performance", "Performance"),
                            ("projects", "Projetos"),
                            ("tasks", "Tarefas"),
                            ("timelogs", "Registros de Tempo"),
                            ("finance", "Finance"),
                            ("crm", "CRM"),
                            ("recruitment", "Recruitment"),
                            ("assets", "Ativos/Bens"),
                            ("tickets", "Tickets/Chamados"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("create", "Create"),
                            ("edit", "Editar"),
                            ("delete", "Deletar"),
                            ("export", "Exportar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_permissions",
                        to="core.usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário Permission",
                "verbose_name_plural": "Permissões do Usuário",
            },
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
        migrations.DeleteModel(
            name="CompanyDomain",
        ),
    ]
