# Generated by Django 5.2.9 on 2025-12-13 02:45

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("assistant", "0001_initial"),
        ("core", "0003_remove_company_subscription_plan_remove_user_company_and_more"),
        ("crm", "0002_alter_client_options_alter_lead_options_and_more"),
        ("finance", "0002_alter_estimate_options_alter_expense_options_and_more"),
        ("hrm", "0002_alter_department_options_alter_designation_options_and_more"),
        ("recruitment", "0002_alter_candidate_options_and_more"),
        (
            "saas_admin",
            "0002_alter_billinginvoice_options_alter_coupon_options_and_more",
        ),
        (
            "security",
            "0002_remove_usersession_company_remove_usersession_user_and_more",
        ),
        ("utilities", "0002_remove_notice_author_remove_notice_company_and_more"),
        ("work", "0002_alter_contract_options_alter_project_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.DeleteModel(
            name="UserPermission",
        ),
        migrations.AlterUniqueTogether(
            name="empresadomain",
            unique_together={("company", "is_primary")},
        ),
        migrations.AlterUniqueTogether(
            name="usuário",
            unique_together={("email", "company")},
        ),
        migrations.AddIndex(
            model_name="auditorialog",
            index=models.Index(
                fields=["company", "-created_at"], name="core_audito_company_d749ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditorialog",
            index=models.Index(
                fields=["user", "-created_at"], name="core_audito_user_id_3e6884_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditorialog",
            index=models.Index(fields=["action"], name="core_audito_action_0665c5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="usuáriopermission",
            unique_together={("company", "user", "module")},
        ),
        migrations.CreateModel(
            name="User",
            fields=[],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.usuário",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
