# Generated by Django 5.1.3 on 2025-12-12 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_auditlog_options_alter_company_options_and_more"),
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"verbose_name": "Ativo/Bem", "verbose_name_plural": "Ativos/Bens"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
            },
        ),
        migrations.AlterModelOptions(
            name="notice",
            options={
                "ordering": ["-is_pinned", "-publish_date"],
                "verbose_name": "Aviso",
                "verbose_name_plural": "Avisos",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "verbose_name": "Ticket/Chamado",
                "verbose_name_plural": "Tickets/Chamados",
            },
        ),
        migrations.AlterModelOptions(
            name="ticketreply",
            options={
                "verbose_name": "Resposta do Ticket",
                "verbose_name_plural": "Respostas do Ticket",
            },
        ),
        migrations.AlterField(
            model_name="asset",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Disponível"),
                    ("in_use", "Em Uso"),
                    ("maintenance", "Manutenção"),
                    ("disposed", "Disposed"),
                    ("lost", "Perdido"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="meeting_link",
            field=models.URLField(blank=True, help_text="Link do Zoom/Google Meet"),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("in_progress", "Em Progresso"),
                    ("completed", "Concluído"),
                    ("cancelled", "Cancelado"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("hr", "HR"),
                    ("technical", "Technical"),
                    ("important", "Importante"),
                    ("event", "Evento"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="is_pinned",
            field=models.BooleanField(
                default=False, help_text="Fixar no topo do quadro de avisos"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("technical", "Technical"),
                    ("billing", "Billing"),
                    ("feature_request", "Solicitação de Recurso"),
                    ("bug_report", "Relatório de Bug"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Baixo"),
                    ("medium", "Médio"),
                    ("high", "Alto"),
                    ("urgent", "Urgente"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Aberto"),
                    ("in_progress", "Em Progresso"),
                    ("waiting_for_customer", "Waiting for Customer"),
                    ("resolved", "Resolvido"),
                    ("closed", "Fechado"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticketreply",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="ticketreply",
            name="is_internal",
            field=models.BooleanField(
                default=False, help_text="Nãota interna, não visível para o cliente"
            ),
        ),
    ]
