# Generated by Django 5.2.9 on 2025-12-13 02:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_company_subscription_plan_remove_user_company_and_more"),
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notice",
            name="author",
        ),
        migrations.RemoveField(
            model_name="notice",
            name="company",
        ),
        migrations.AlterModelOptions(
            name="asset",
            options={"verbose_name": "Ativo/Bem", "verbose_name_plural": "Ativos/Bens"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "verbose_name": "Ticket/Chamado",
                "verbose_name_plural": "Tickets/Chamados",
            },
        ),
        migrations.AlterModelOptions(
            name="ticketreply",
            options={
                "verbose_name": "Resposta do Ticket",
                "verbose_name_plural": "Respostas do Ticket",
            },
        ),
        migrations.AlterField(
            model_name="asset",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Disponível"),
                    ("in_use", "Em Uso"),
                    ("maintenance", "Manutenção"),
                    ("disposed", "Disposed"),
                    ("lost", "Perdido"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True, related_name="events_attending", to="core.usuário"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="meeting_link",
            field=models.URLField(blank=True, help_text="Link do Zoom/Google Meet"),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_organized",
                to="core.usuário",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("in_progress", "Em Progresso"),
                    ("completed", "Concluído"),
                    ("cancelled", "Cancelarado"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_assigned",
                to="core.usuário",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("technical", "Technical"),
                    ("billing", "Billing"),
                    ("feature_request", "Solicitação de Recurso"),
                    ("bug_report", "Relatório de Bug"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_created",
                to="core.usuário",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Baixo"),
                    ("medium", "Médio"),
                    ("high", "Alto"),
                    ("urgent", "Urgente"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Aberto"),
                    ("in_progress", "Em Progresso"),
                    ("waiting_for_customer", "Waiting for Customer"),
                    ("resolved", "Resolvido"),
                    ("closed", "Fechado"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticketreply",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_replies",
                to="core.usuário",
            ),
        ),
        migrations.AlterField(
            model_name="ticketreply",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="ticketreply",
            name="is_internal",
            field=models.BooleanField(
                default=False, help_text="Nãota interna, não visível para o cliente"
            ),
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_received",
                        to="core.usuário",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_sent",
                        to="core.usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Nãotice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("hr", "HR"),
                            ("technical", "Technical"),
                            ("important", "Importarante"),
                            ("event", "Evento"),
                        ],
                        max_length=50,
                    ),
                ),
                ("publish_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False, help_text="Fixar no topo do quadro de avisos"
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices_created",
                        to="core.usuário",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Tenant) a qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_company",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aviso",
                "verbose_name_plural": "Avisos",
                "ordering": ["-is_pinned", "-publish_date"],
            },
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Notice",
        ),
    ]
