# Generated by Django 5.1.3 on 2025-12-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0002_alter_asset_options_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("hardware", "Hardware"),
                    ("software", "Software"),
                    ("furniture", "Mobiliário"),
                    ("vehicle", "Veículo"),
                    ("other", "Outros"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Disponível"),
                    ("in_use", "Em Uso"),
                    ("maintenance", "Manutenção"),
                    ("disposed", "Descartado"),
                    ("lost", "Perdido"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("meeting", "Reunião"),
                    ("conference", "Conferência"),
                    ("training", "Treinamento"),
                    ("social", "Social"),
                    ("holiday", "Feriado"),
                    ("other", "Outros"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Agendado"),
                    ("in_progress", "Em Progresso"),
                    ("completed", "Concluído"),
                    ("cancelled", "Cancelado"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "Geral"),
                    ("hr", "RH"),
                    ("technical", "Técnico"),
                    ("important", "Importante"),
                    ("event", "Evento"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("technical", "Técnico"),
                    ("billing", "Faturamento"),
                    ("feature_request", "Solicitação de Recurso"),
                    ("bug_report", "Relatório de Bug"),
                    ("other", "Outros"),
                ],
                max_length=100,
            ),
        ),
    ]
