# Generated by Django 5.2.9 on 2025-12-13 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departamento_pessoal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colaborador_dp",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ItemFolha",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("codigo", models.CharField(max_length=20)),
                ("descricao", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("provento", "Provento"), ("desconto", "Desconto")],
                        max_length=20,
                    ),
                ),
                (
                    "referencia",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "folha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="departamento_pessoal.folhapagamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Folha",
                "verbose_name_plural": "Itens da Folha",
                "ordering": ["tipo", "codigo"],
            },
        ),
    ]
