# Generated by Django 5.1.3 on 2025-12-12 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_auditlog_options_alter_company_options_and_more"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Cliente", "verbose_name_plural": "Clientes"},
        ),
        migrations.AlterModelOptions(
            name="lead",
            options={
                "verbose_name": "Lead/Oportunidade",
                "verbose_name_plural": "Leads/Oportunidades",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Pedido", "verbose_name_plural": "Pedidos"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens do Pedido",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Produto", "verbose_name_plural": "Produtos"},
        ),
        migrations.AlterField(
            model_name="client",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("prospect", "Perspectiva"),
                    ("qualified", "Qualificado"),
                    ("active", "Ativo"),
                    ("inactive", "Inativo"),
                    ("blocked", "Bloqueado"),
                ],
                default="prospect",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="probability",
            field=models.IntegerField(
                default=50, help_text="Probabilidade de fechamento %"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("referral", "Referral"),
                    ("cold_call", "Cold Call"),
                    ("email", "Email"),
                    ("social_media", "Social Media"),
                    ("event", "Evento"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="stage",
            field=models.CharField(
                choices=[
                    ("new", "Nãovo"),
                    ("contacted", "Contacted"),
                    ("qualified", "Qualificado"),
                    ("proposal", "Proposal Sent"),
                    ("negotiation", "Negociação"),
                    ("closed_won", "Fechard Won"),
                    ("closed_lost", "Fechard Lost"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("confirmed", "Confirmed"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelado"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("service", "Service"),
                    ("product", "Produto"),
                    ("subscription", "Assinatura"),
                    ("license", "License"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativo"),
                    ("inactive", "Inativo"),
                    ("discontinued", "Discontinued"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
