# Generated by Django 5.1.3 on 2025-12-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_client_options_alter_lead_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "Site"),
                    ("referral", "Indicação"),
                    ("cold_call", "Cold Call"),
                    ("email", "Email"),
                    ("social_media", "Redes Sociais"),
                    ("event", "Evento"),
                    ("other", "Outros"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="stage",
            field=models.CharField(
                choices=[
                    ("new", "Novo"),
                    ("contacted", "Contatado"),
                    ("qualified", "Qualificado"),
                    ("proposal", "Proposta Enviada"),
                    ("negotiation", "Negociação"),
                    ("closed_won", "Fechado Ganho"),
                    ("closed_lost", "Fechado Perdido"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("confirmed", "Confirmado"),
                    ("processing", "Processando"),
                    ("shipped", "Enviado"),
                    ("delivered", "Entregue"),
                    ("cancelled", "Cancelado"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("service", "Serviço"),
                    ("product", "Produto"),
                    ("subscription", "Assinatura"),
                    ("license", "Licença"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativo"),
                    ("inactive", "Inativo"),
                    ("discontinued", "Descontinuado"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
