# Generated by Django 5.2.9 on 2025-12-13 00:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departamento_pessoal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DimensaoClima",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "peso",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("ordem", models.IntegerField(default=0)),
                (
                    "score_medio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Dimensão de Clima",
                "verbose_name_plural": "Dimensões de Clima",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="PesquisaeNPS",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "pergunta_principal",
                    models.TextField(
                        default="Em uma escala de 0 a 10, o quanto você recomendaria nossa empresa como um bom lugar para trabalhar?"
                    ),
                ),
                ("perguntas_abertas", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("em_andamento", "Em Andamento"),
                            ("encerrada", "Encerrada"),
                        ],
                        default="rascunho",
                        max_length=30,
                    ),
                ),
                ("total_respostas", models.IntegerField(default=0)),
                ("promotores", models.IntegerField(default=0)),
                ("neutros", models.IntegerField(default=0)),
                ("detratores", models.IntegerField(default=0)),
                (
                    "score_enps",
                    models.IntegerField(blank=True, help_text="-100 a 100", null=True),
                ),
            ],
            options={
                "verbose_name": "Pesquisa eNPS",
                "verbose_name_plural": "Pesquisas eNPS",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="PlanoCarreira",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "trilha",
                    models.JSONField(
                        default=list, help_text="Lista ordenada de cargos na trilha"
                    ),
                ),
                (
                    "requisitos_transicao",
                    models.JSONField(
                        default=dict, help_text="Requisitos para cada transição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Carreira",
                "verbose_name_plural": "Planos de Carreira",
            },
        ),
        migrations.CreateModel(
            name="TabelaSalarial",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("data_vigencia", models.DateField()),
            ],
            options={
                "verbose_name": "Tabela Salarial",
                "verbose_name_plural": "Tabelas Salariais",
                "ordering": ["-data_vigencia"],
            },
        ),
        migrations.CreateModel(
            name="TipoBeneficio",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("alimentacao", "Alimentação"),
                            ("transporte", "Transporte"),
                            ("saude", "Saúde"),
                            ("educacao", "Educação"),
                            ("bem_estar", "Bem-estar"),
                            ("financeiro", "Financeiro"),
                            ("outros", "Outros"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "valor_padrao",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valor_desconto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "percentual_desconto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("fornecedor", models.CharField(blank=True, max_length=255)),
                (
                    "elegibilidade",
                    models.CharField(
                        choices=[
                            ("todos", "Todos os Colaboradores"),
                            ("clt", "Apenas CLT"),
                            ("gestor", "Apenas Gestores"),
                            ("seletivo", "Seletivo"),
                        ],
                        default="todos",
                        max_length=50,
                    ),
                ),
                ("obrigatorio", models.BooleanField(default=False)),
                (
                    "flexivel",
                    models.BooleanField(
                        default=False, help_text="Permite escolha do colaborador"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Benefício",
                "verbose_name_plural": "Tipos de Benefícios",
            },
        ),
        migrations.CreateModel(
            name="AnaliseDemissional",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("data_demissao", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("voluntaria", "Demissão Voluntária"),
                            ("involuntaria", "Demissão Involuntária"),
                            ("acordo", "Acordo Mútuo"),
                            ("termino_contrato", "Término de Contrato"),
                            ("aposentadoria", "Aposentadoria"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "motivo_principal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("proposta_melhor", "Proposta Melhor"),
                            ("remuneracao", "Insatisfação com Remuneração"),
                            ("carreira", "Falta de Crescimento"),
                            ("gestao", "Problemas com Gestão"),
                            ("clima", "Clima Organizacional"),
                            ("beneficios", "Benefícios"),
                            ("localizacao", "Localização/Deslocamento"),
                            ("pessoal", "Motivos Pessoais"),
                            ("desempenho", "Desempenho"),
                            ("outros", "Outros"),
                        ],
                        max_length=100,
                    ),
                ),
                ("motivos_detalhados", models.TextField(blank=True)),
                ("entrevista_realizada", models.BooleanField(default=False)),
                ("data_entrevista", models.DateField(blank=True, null=True)),
                ("recomendaria_empresa", models.BooleanField(blank=True, null=True)),
                ("voltaria_empresa", models.BooleanField(blank=True, null=True)),
                (
                    "nota_experiencia",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("pontos_positivos", models.TextField(blank=True)),
                ("pontos_negativos", models.TextField(blank=True)),
                ("sugestoes_melhoria", models.TextField(blank=True)),
                ("insights_ia", models.JSONField(blank=True, default=list)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analises_demissionais",
                        to="departamento_pessoal.colaborador",
                    ),
                ),
                (
                    "entrevistador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Análise Demissional",
                "verbose_name_plural": "Análises Demissionais",
                "ordering": ["-data_demissao"],
            },
        ),
        migrations.CreateModel(
            name="AnaliseRotatividade",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("data_analise", models.DateField(auto_now_add=True)),
                (
                    "score_risco",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "classificacao",
                    models.CharField(
                        choices=[
                            ("baixo", "Baixo (0-25)"),
                            ("medio", "Médio (26-50)"),
                            ("alto", "Alto (51-75)"),
                            ("critico", "Crítico (76-100)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fatores",
                    models.JSONField(
                        default=list, help_text="Lista de fatores que aumentam o risco"
                    ),
                ),
                (
                    "indicadores",
                    models.JSONField(
                        default=dict, help_text="Indicadores que compõem o score"
                    ),
                ),
                ("recomendacoes", models.JSONField(default=list)),
                ("score_anterior", models.IntegerField(blank=True, null=True)),
                (
                    "tendencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("subindo", "Subindo ↑"),
                            ("estavel", "Estável →"),
                            ("descendo", "Descendo ↓"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analises_rotatividade",
                        to="departamento_pessoal.colaborador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análise de Rotatividade",
                "verbose_name_plural": "Análises de Rotatividade",
                "ordering": ["-data_analise"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackRapido",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("positivo", "Feedback Positivo"),
                            ("construtivo", "Feedback Construtivo"),
                            ("solicitado", "Feedback Solicitado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("conteudo", models.TextField()),
                ("privado", models.BooleanField(default=True)),
                ("visualizado", models.BooleanField(default=False)),
                ("data_visualizacao", models.DateTimeField(blank=True, null=True)),
                (
                    "de_colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks_dados",
                        to="departamento_pessoal.colaborador",
                    ),
                ),
                (
                    "para_colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks_recebidos",
                        to="departamento_pessoal.colaborador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Rápido",
                "verbose_name_plural": "Feedbacks Rápidos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InsightEngajamento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("clima", "Análise de Clima"),
                            ("enps", "Análise eNPS"),
                            ("rotatividade", "Previsão de Rotatividade"),
                            ("engajamento", "Nível de Engajamento"),
                            ("padrao", "Padrão Identificado"),
                            ("acao_sugerida", "Ação Sugerida"),
                        ],
                        max_length=50,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("dados_suporte", models.JSONField(blank=True, default=dict)),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                ("acao_sugerida", models.TextField(blank=True)),
                ("acao_tomada", models.BooleanField(default=False)),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="departamento_pessoal.colaborador",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="departamento_pessoal.departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insight de Engajamento",
                "verbose_name_plural": "Insights de Engajamento",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificacaoColaborador",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                ("mensagem", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("info", "Informação"),
                            ("alerta", "Alerta"),
                            ("urgente", "Urgente"),
                            ("lembrete", "Lembrete"),
                            ("parabens", "Parabéns"),
                            ("feedback", "Feedback"),
                            ("ponto", "Ponto"),
                            ("ferias", "Férias"),
                            ("treinamento", "Treinamento"),
                            ("pesquisa", "Pesquisa"),
                        ],
                        max_length=50,
                    ),
                ),
                ("link_acao", models.CharField(blank=True, max_length=255)),
                ("lida", models.BooleanField(default=False)),
                ("data_leitura", models.DateTimeField(blank=True, null=True)),
                ("data_expiracao", models.DateTimeField(blank=True, null=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to="departamento_pessoal.colaborador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerguntaClima",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("texto", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("escala", "Escala (1-5)"),
                            ("escala_10", "Escala (1-10)"),
                            ("sim_nao", "Sim/Não"),
                            ("multipla", "Múltipla Escolha"),
                            ("aberta", "Resposta Aberta"),
                        ],
                        default="escala",
                        max_length=30,
                    ),
                ),
                ("obrigatoria", models.BooleanField(default=True)),
                (
                    "opcoes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Opções para múltipla escolha",
                    ),
                ),
                ("ordem", models.IntegerField(default=0)),
                (
                    "media_respostas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "dimensao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perguntas",
                        to="engajamento_retencao.dimensaoclima",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pergunta de Clima",
                "verbose_name_plural": "Perguntas de Clima",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="PesquisaClima",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("anonima", models.BooleanField(default=True)),
                ("obrigatoria", models.BooleanField(default=False)),
                ("todos_colaboradores", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("agendada", "Agendada"),
                            ("em_andamento", "Em Andamento"),
                            ("encerrada", "Encerrada"),
                            ("analisada", "Analisada"),
                        ],
                        default="rascunho",
                        max_length=30,
                    ),
                ),
                (
                    "taxa_participacao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "score_geral",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pesquisas_clima_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departamentos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pesquisas_clima",
                        to="departamento_pessoal.departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pesquisa de Clima",
                "verbose_name_plural": "Pesquisas de Clima",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.AddField(
            model_name="dimensaoclima",
            name="pesquisa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dimensoes",
                to="engajamento_retencao.pesquisaclima",
            ),
        ),
        migrations.CreateModel(
            name="PlanoAcaoClima",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejado", "Planejado"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="planejado",
                        max_length=30,
                    ),
                ),
                (
                    "progresso",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("sugerido_ia", models.BooleanField(default=False)),
                (
                    "dimensao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="engajamento_retencao.dimensaoclima",
                    ),
                ),
                (
                    "pesquisa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planos_acao",
                        to="engajamento_retencao.pesquisaclima",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planos_acao_clima",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Ação (Clima)",
                "verbose_name_plural": "Planos de Ação (Clima)",
            },
        ),
        migrations.CreateModel(
            name="Reconhecimento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("obrigado", "Obrigado"),
                            ("parabens", "Parabéns"),
                            ("inspiracao", "Inspiração"),
                            ("trabalho_equipe", "Trabalho em Equipe"),
                            ("inovacao", "Inovação"),
                            ("lideranca", "Liderança"),
                            ("ajuda", "Ajuda"),
                        ],
                        max_length=50,
                    ),
                ),
                ("mensagem", models.TextField()),
                ("publico", models.BooleanField(default=True)),
                ("pontos", models.IntegerField(default=10)),
                (
                    "de_colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconhecimentos_dados",
                        to="departamento_pessoal.colaborador",
                    ),
                ),
                (
                    "para_colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconhecimentos_recebidos",
                        to="departamento_pessoal.colaborador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reconhecimento",
                "verbose_name_plural": "Reconhecimentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RespostaClima",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "respostas",
                    models.JSONField(
                        default=dict, help_text="Dict {pergunta_id: resposta}"
                    ),
                ),
                ("data_resposta", models.DateTimeField(auto_now_add=True)),
                (
                    "tempo_preenchimento",
                    models.IntegerField(default=0, help_text="Segundos"),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="respostas_clima",
                        to="departamento_pessoal.colaborador",
                    ),
                ),
                (
                    "pesquisa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="engajamento_retencao.pesquisaclima",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta de Clima",
                "verbose_name_plural": "Respostas de Clima",
            },
        ),
        migrations.CreateModel(
            name="RespostaeNPS",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "nota",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "classificacao",
                    models.CharField(
                        choices=[
                            ("promotor", "Promotor (9-10)"),
                            ("neutro", "Neutro (7-8)"),
                            ("detrator", "Detrator (0-6)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comentarios", models.TextField(blank=True)),
                ("respostas_adicionais", models.JSONField(blank=True, default=dict)),
                ("data_resposta", models.DateTimeField(auto_now_add=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="departamento_pessoal.colaborador",
                    ),
                ),
                (
                    "pesquisa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="engajamento_retencao.pesquisaenps",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta eNPS",
                "verbose_name_plural": "Respostas eNPS",
            },
        ),
        migrations.CreateModel(
            name="SolicitacaoPromocao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("promocao", "Promoção"),
                            ("merito", "Aumento por Mérito"),
                            ("enquadramento", "Enquadramento"),
                            ("reajuste", "Reajuste"),
                        ],
                        max_length=30,
                    ),
                ),
                ("salario_atual", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "salario_proposto",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "percentual_aumento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("justificativa", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("pendente_gestor", "Pendente Gestor"),
                            ("aprovado_gestor", "Aprovado Gestor"),
                            ("pendente_rh", "Pendente RH"),
                            ("aprovado_rh", "Aprovado RH"),
                            ("pendente_diretoria", "Pendente Diretoria"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                            ("efetivado", "Efetivado"),
                        ],
                        default="rascunho",
                        max_length=30,
                    ),
                ),
                ("data_efetivacao", models.DateField(blank=True, null=True)),
                (
                    "cargo_atual",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promocoes_de",
                        to="departamento_pessoal.cargo",
                    ),
                ),
                (
                    "cargo_proposto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promocoes_para",
                        to="departamento_pessoal.cargo",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_promocao",
                        to="departamento_pessoal.colaborador",
                    ),
                ),
                (
                    "solicitado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promocoes_solicitadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Promoção",
                "verbose_name_plural": "Solicitações de Promoção",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BeneficioColaborador",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valor_desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("suspenso", "Suspenso"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="ativo",
                        max_length=30,
                    ),
                ),
                ("dependentes", models.JSONField(blank=True, default=list)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficios",
                        to="departamento_pessoal.colaborador",
                    ),
                ),
                (
                    "tipo_beneficio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atribuicoes",
                        to="engajamento_retencao.tipobeneficio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benefício do Colaborador",
                "verbose_name_plural": "Benefícios dos Colaboradores",
            },
        ),
        migrations.CreateModel(
            name="FaixaSalarial",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "salario_minimo",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("salario_medio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "salario_maximo",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "steps",
                    models.JSONField(
                        default=list, help_text="Lista de valores de steps"
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faixas_salariais",
                        to="departamento_pessoal.cargo",
                    ),
                ),
                (
                    "tabela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faixas",
                        to="engajamento_retencao.tabelasalarial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faixa Salarial",
                "verbose_name_plural": "Faixas Salariais",
                "unique_together": {("tabela", "cargo")},
            },
        ),
    ]
