# Generated by Django 5.2.9 on 2025-12-12 23:05

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelixConfig",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Ativar SyncRH para esta empresa"
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        default="Você é o assistente virtual do sistema SyncRH. Responda de forma concisa, profissional e sempre baseando-se estritamente no contexto fornecido. Se não souber a resposta, diga que precisa de ajuda de um humano.",
                        help_text="Prompt de sistema para LLM (Português)",
                    ),
                ),
                (
                    "max_context_chunks",
                    models.IntegerField(
                        default=5,
                        help_text="Número máximo de chunks de documento para usar como contexto",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.3, help_text="Temperatura do LLM (0,0 a 1,0)"
                    ),
                ),
                (
                    "enable_citation",
                    models.BooleanField(
                        default=True,
                        help_text="Incluir citações de fonte nas respostas",
                    ),
                ),
                (
                    "similarity_threshold",
                    models.FloatField(
                        default=0.7,
                        help_text="Escore mínimo de similaridade para chunks relevantes (0,0 a 1,0)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração do SyncRH",
                "verbose_name_plural": "Configurações do SyncRH",
            },
        ),
        migrations.CreateModel(
            name="Conversa",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Título da conversa gerado automaticamente",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Marcar como arquivado"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversa",
                "verbose_name_plural": "Conversas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Título do documento (ex: 'Guia de Instalação')",
                        max_length=255,
                    ),
                ),
                (
                    "source_path",
                    models.CharField(
                        help_text="Caminho original do arquivo (ex: 'docs/setup.md')",
                        max_length=500,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Conteúdo completo do documento"),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("markdown", "Markdown"),
                            ("text", "Plain Text"),
                            ("html", "HTML"),
                        ],
                        default="markdown",
                        max_length=50,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", help_text="Versão do documento", max_length=20
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Incluir na base de conhecimento RAG"
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentoos",
                "ordering": ["-ingested_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="assistant_d_is_acti_a3c447_idx"
                    ),
                    models.Index(
                        fields=["source_path"], name="assistant_d_source__86375d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentoChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(
                        help_text="Número sequencial do chunk dentro do documento"
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Conteúdo de texto deste chunk"),
                ),
                (
                    "embedding",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        blank=True,
                        help_text="Vetor de embedding da OpenAI (1536 dimensões para text-embedding-3-small)",
                        null=True,
                        size=1536,
                    ),
                ),
                (
                    "token_count",
                    models.IntegerField(
                        default=0, help_text="Contagem de tokens para este chunk"
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="text-embedding-3-small",
                        help_text="Modelo OpenAI usado para embedding",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="assistant.documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fragmento de Documentoo",
                "verbose_name_plural": "Fragmentos de Documentoos",
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Usuário"),
                            ("assistant", "Assistant (SyncRH)"),
                            ("system", "System"),
                        ],
                        help_text="Quem enviou a mensagem",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Conteúdo da mensagem")),
                (
                    "context_sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Documentoos/chunks usados para resposta (contexto RAG)",
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        default=0,
                        help_text="Tokens OpenAI consumidos por esta mensagem",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="assistant.conversa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conversa",
            index=models.Index(
                fields=["user", "-created_at"], name="assistant_c_user_id_8ad2a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentochunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="assistant_d_documen_c971b0_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentochunk",
            unique_together={("document", "chunk_index")},
        ),
        migrations.AddIndex(
            model_name="mensagem",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="assistant_m_convers_b43010_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mensagem",
            index=models.Index(fields=["role"], name="assistant_m_role_3c14e6_idx"),
        ),
    ]
