# Generated by Django 5.1.3 on 2025-12-03 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='company',
            field=models.ForeignKey(help_text='Company (Tenant) this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='core.company'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.ForeignKey(help_text='Company (Tenant) this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='core.company'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='assistant.document'),
        ),
        migrations.AddField(
            model_name='helixconfig',
            name='company',
            field=models.ForeignKey(help_text='Company (Tenant) this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='core.company'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'company', '-created_at'], name='assistant_c_user_id_94fe96_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'is_active'], name='assistant_d_company_cc9259_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['source_path'], name='assistant_d_source__2b06b2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='assistant_d_documen_56c10c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
        migrations.AlterUniqueTogether(
            name='helixconfig',
            unique_together={('company',)},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='assistant_m_convers_dbe832_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role'], name='assistant_m_role_34372f_idx'),
        ),
    ]
