# Generated by Django 5.2.9 on 2025-12-13 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assistant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversa",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistant_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["is_active"], name="assistant_d_is_acti_a3c447_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["source_path"], name="assistant_d_source__86375d_idx"
            ),
        ),
        migrations.AddField(
            model_name="documentochunk",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="assistant.documento",
            ),
        ),
        migrations.AddField(
            model_name="mensagem",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="assistant.conversa",
            ),
        ),
        migrations.AddIndex(
            model_name="conversa",
            index=models.Index(
                fields=["user", "-created_at"], name="assistant_c_user_id_8ad2a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentochunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="assistant_d_documen_c971b0_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentochunk",
            unique_together={("document", "chunk_index")},
        ),
        migrations.AddIndex(
            model_name="mensagem",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="assistant_m_convers_b43010_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mensagem",
            index=models.Index(fields=["role"], name="assistant_m_role_3c14e6_idx"),
        ),
    ]
