# Generated by Django 5.1.3 on 2025-12-12 21:44

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0002_initial"),
        ("core", "0003_alter_auditlog_options_alter_company_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Conversa",
                "verbose_name_plural": "Conversas",
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-ingested_at"],
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
            },
        ),
        migrations.AlterModelOptions(
            name="documentchunk",
            options={
                "ordering": ["document", "chunk_index"],
                "verbose_name": "Fragmento de Documento",
                "verbose_name_plural": "Fragmentos de Documentos",
            },
        ),
        migrations.AlterModelOptions(
            name="helixconfig",
            options={
                "verbose_name": "Configuração do SyncRH",
                "verbose_name_plural": "Configurações do SyncRH",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
            },
        ),
        migrations.AlterField(
            model_name="conversation",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Marcar como arquivado"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Título da conversa gerado automaticamente",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.TextField(help_text="Conteúdo completo do documento"),
        ),
        migrations.AlterField(
            model_name="document",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Incluir na base de conhecimento RAG"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="source_path",
            field=models.CharField(
                help_text="Caminho original do arquivo (ex: 'docs/setup.md')",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(
                help_text="Título do documento (ex: 'Guia de Instalação')",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="version",
            field=models.CharField(
                default="1.0", help_text="Versão do documento", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="chunk_index",
            field=models.IntegerField(
                help_text="Número sequencial do chunk dentro do documento"
            ),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="content",
            field=models.TextField(help_text="Conteúdo de texto deste chunk"),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                blank=True,
                help_text="Vetor de embedding da OpenAI (1536 dimensões para text-embedding-3-small)",
                null=True,
                size=1536,
            ),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding_model",
            field=models.CharField(
                default="text-embedding-3-small",
                help_text="Modelo OpenAI usado para embedding",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="token_count",
            field=models.IntegerField(
                default=0, help_text="Contagem de tokens para este chunk"
            ),
        ),
        migrations.AlterField(
            model_name="helixconfig",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="helixconfig",
            name="enable_citation",
            field=models.BooleanField(
                default=True, help_text="Incluir citações de fonte nas respostas"
            ),
        ),
        migrations.AlterField(
            model_name="helixconfig",
            name="is_enabled",
            field=models.BooleanField(
                default=True, help_text="Ativar SyncRH para esta empresa"
            ),
        ),
        migrations.AlterField(
            model_name="helixconfig",
            name="max_context_chunks",
            field=models.IntegerField(
                default=5,
                help_text="Número máximo de chunks de documento para usar como contexto",
            ),
        ),
        migrations.AlterField(
            model_name="helixconfig",
            name="similarity_threshold",
            field=models.FloatField(
                default=0.7,
                help_text="Escore mínimo de similaridade para chunks relevantes (0,0 a 1,0)",
            ),
        ),
        migrations.AlterField(
            model_name="helixconfig",
            name="system_prompt",
            field=models.TextField(
                default="Você é o assistente virtual do sistema SyncRH. Responda de forma concisa, profissional e sempre baseando-se estritamente no contexto fornecido. Se não souber a resposta, diga que precisa de ajuda de um humano.",
                help_text="Prompt de sistema para LLM (Português)",
            ),
        ),
        migrations.AlterField(
            model_name="helixconfig",
            name="temperature",
            field=models.FloatField(
                default=0.3, help_text="Temperatura do LLM (0,0 a 1,0)"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(help_text="Conteúdo da mensagem"),
        ),
        migrations.AlterField(
            model_name="message",
            name="context_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Documentos/chunks usados para resposta (contexto RAG)",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Usuário"),
                    ("assistant", "Assistant (SyncRH)"),
                    ("system", "System"),
                ],
                help_text="Quem enviou a mensagem",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="tokens_used",
            field=models.IntegerField(
                default=0, help_text="Tokens OpenAI consumidos por esta mensagem"
            ),
        ),
    ]
