# Generated by Django 5.2.9 on 2025-12-13 00:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departamento_pessoal", "0001_initial"),
        ("recrutamento_selecao", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetenciaComportamental",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("lideranca", "Liderança"),
                            ("comunicacao", "Comunicação"),
                            ("relacionamento", "Relacionamento"),
                            ("execucao", "Execução"),
                            ("analise", "Análise"),
                            ("adaptabilidade", "Adaptabilidade"),
                            ("inovacao", "Inovação"),
                            ("organizacao", "Organização"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "disc_relacionado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("D", "Dominância"),
                            ("I", "Influência"),
                            ("S", "Estabilidade"),
                            ("C", "Conformidade"),
                            ("DI", "Dominância/Influência"),
                            ("DC", "Dominância/Conformidade"),
                            ("IS", "Influência/Estabilidade"),
                            ("SC", "Estabilidade/Conformidade"),
                        ],
                        max_length=4,
                    ),
                ),
                ("indicadores_positivos", models.JSONField(default=list)),
                ("indicadores_negativos", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "Competência Comportamental",
                "verbose_name_plural": "Competências Comportamentais",
                "ordering": ["categoria", "nome"],
            },
        ),
        migrations.CreateModel(
            name="QuestionarioProfiler",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("versao", models.CharField(default="1.0", max_length=20)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("disc", "DISC Clássico"),
                            ("disc_extendido", "DISC Estendido"),
                            ("big5", "Big Five"),
                            ("mbti", "MBTI Simplificado"),
                            ("personalizado", "Personalizado"),
                        ],
                        default="disc",
                        max_length=30,
                    ),
                ),
                (
                    "tempo_estimado",
                    models.IntegerField(default=15, help_text="Minutos"),
                ),
                ("total_questoes", models.IntegerField(default=24)),
                ("instrucoes", models.TextField(blank=True)),
                ("publicado", models.BooleanField(default=False)),
                ("data_publicacao", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Questionário Profiler",
                "verbose_name_plural": "Questionários Profiler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AplicacaoProfiler",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("expirado", "Expirado"),
                        ],
                        default="pendente",
                        max_length=30,
                    ),
                ),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                ("data_inicio", models.DateTimeField(blank=True, null=True)),
                ("data_conclusao", models.DateTimeField(blank=True, null=True)),
                ("data_expiracao", models.DateTimeField(blank=True, null=True)),
                ("tempo_total", models.IntegerField(default=0, help_text="Segundos")),
                ("token_acesso", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "candidato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicacoes_profiler",
                        to="recrutamento_selecao.candidato",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicacoes_profiler",
                        to="departamento_pessoal.colaborador",
                    ),
                ),
                (
                    "questionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicacoes",
                        to="gestao_comportamental.questionarioprofiler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aplicação Profiler",
                "verbose_name_plural": "Aplicações Profiler",
                "ordering": ["-data_envio"],
            },
        ),
        migrations.CreateModel(
            name="InsightComportamental",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("compatibilidade", "Compatibilidade Cargo"),
                            ("desenvolvimento", "Recomendação de Desenvolvimento"),
                            ("time", "Dinâmica de Time"),
                            ("lideranca", "Estilo de Liderança"),
                            ("comunicacao", "Estilo de Comunicação"),
                            ("conflito", "Gestão de Conflitos"),
                            ("padrao", "Padrão Identificado"),
                        ],
                        max_length=50,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("dados_suporte", models.JSONField(blank=True, default=dict)),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                ("acao_sugerida", models.TextField(blank=True)),
                ("acao_tomada", models.BooleanField(default=False)),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights_comportamentais",
                        to="departamento_pessoal.colaborador",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights_comportamentais",
                        to="departamento_pessoal.departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insight Comportamental",
                "verbose_name_plural": "Insights Comportamentais",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MetricaProfiler",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("data_referencia", models.DateField()),
                ("total_aplicacoes", models.IntegerField(default=0)),
                ("total_concluidos", models.IntegerField(default=0)),
                (
                    "taxa_conclusao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "media_dominancia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "media_influencia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "media_estabilidade",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "media_conformidade",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "distribuicao_perfis",
                    models.JSONField(
                        default=dict,
                        help_text='Ex: {"D": 10, "I": 15, "S": 8, "C": 12}',
                    ),
                ),
                (
                    "media_match",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Média de match com perfil ideal",
                        max_digits=5,
                    ),
                ),
                (
                    "tempo_medio_resposta",
                    models.IntegerField(default=0, help_text="Segundos"),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departamento_pessoal.cargo",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departamento_pessoal.departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Métrica Profiler",
                "verbose_name_plural": "Métricas Profiler",
                "ordering": ["-data_referencia"],
            },
        ),
        migrations.CreateModel(
            name="PerfilDISC",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "dominancia",
                    models.IntegerField(
                        help_text="D - Dominância",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "influencia",
                    models.IntegerField(
                        help_text="I - Influência",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "estabilidade",
                    models.IntegerField(
                        help_text="S - Estabilidade",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "conformidade",
                    models.IntegerField(
                        help_text="C - Conformidade",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "tipo_perfil",
                    models.CharField(
                        choices=[
                            ("natural", "Perfil Natural"),
                            ("adaptado", "Perfil Adaptado"),
                        ],
                        default="natural",
                        max_length=20,
                    ),
                ),
                (
                    "perfil_principal",
                    models.CharField(
                        blank=True, help_text="Ex: D, DI, DC, etc.", max_length=4
                    ),
                ),
                (
                    "padrao",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Executor, Comunicador, etc.",
                        max_length=50,
                    ),
                ),
                ("pontos_fortes", models.JSONField(default=list)),
                ("areas_desenvolvimento", models.JSONField(default=list)),
                ("estilo_comunicacao", models.TextField(blank=True)),
                ("estilo_lideranca", models.TextField(blank=True)),
                ("ambiente_ideal", models.TextField(blank=True)),
                ("fatores_motivacao", models.JSONField(default=list)),
                ("fatores_desmotivacao", models.JSONField(default=list)),
                (
                    "indice_consistencia",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "aplicacao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_disc",
                        to="gestao_comportamental.aplicacaoprofiler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil DISC",
                "verbose_name_plural": "Perfis DISC",
            },
        ),
        migrations.CreateModel(
            name="HistoricoPerfilColaborador",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "contexto",
                    models.CharField(
                        choices=[
                            ("admissao", "Admissão"),
                            ("promocao", "Promoção"),
                            ("periodico", "Avaliação Periódica"),
                            ("transferencia", "Transferência"),
                            ("desenvolvimento", "Programa de Desenvolvimento"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("variacao_dominancia", models.IntegerField(default=0)),
                ("variacao_influencia", models.IntegerField(default=0)),
                ("variacao_estabilidade", models.IntegerField(default=0)),
                ("variacao_conformidade", models.IntegerField(default=0)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_perfis",
                        to="departamento_pessoal.colaborador",
                    ),
                ),
                (
                    "perfil_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historicos_posteriores",
                        to="gestao_comportamental.perfildisc",
                    ),
                ),
                (
                    "perfil_disc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historicos",
                        to="gestao_comportamental.perfildisc",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Perfil",
                "verbose_name_plural": "Históricos de Perfis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComparacaoTime",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                (
                    "mapa_time",
                    models.JSONField(
                        default=dict, help_text="Visualização do time no gráfico DISC"
                    ),
                ),
                (
                    "gaps_identificados",
                    models.JSONField(
                        default=list, help_text="Perfis que faltam no time"
                    ),
                ),
                ("pontos_fortes_time", models.JSONField(default=list)),
                ("pontos_atencao_time", models.JSONField(default=list)),
                ("recomendacoes_contratacao", models.TextField(blank=True)),
                ("recomendacoes_desenvolvimento", models.TextField(blank=True)),
                ("analise_ia", models.TextField(blank=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="departamento_pessoal.departamento",
                    ),
                ),
                (
                    "perfis",
                    models.ManyToManyField(
                        related_name="comparacoes",
                        to="gestao_comportamental.perfildisc",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comparação de Time",
                "verbose_name_plural": "Comparações de Times",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerfilIdealCargo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "dominancia_min",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "dominancia_ideal",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "dominancia_max",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "influencia_min",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "influencia_ideal",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "influencia_max",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "estabilidade_min",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "estabilidade_ideal",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "estabilidade_max",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "conformidade_min",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "conformidade_ideal",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "conformidade_max",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "peso_dominancia",
                    models.IntegerField(
                        default=25,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "peso_influencia",
                    models.IntegerField(
                        default=25,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "peso_estabilidade",
                    models.IntegerField(
                        default=25,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "peso_conformidade",
                    models.IntegerField(
                        default=25,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "competencias",
                    models.JSONField(
                        default=list, help_text="Lista de competências comportamentais"
                    ),
                ),
                ("descricao_perfil", models.TextField(blank=True)),
                ("data_definicao", models.DateTimeField(auto_now_add=True)),
                (
                    "cargo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_ideal",
                        to="departamento_pessoal.cargo",
                    ),
                ),
                (
                    "definido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil Ideal do Cargo",
                "verbose_name_plural": "Perfis Ideais dos Cargos",
            },
        ),
        migrations.CreateModel(
            name="QuestaoProfiler",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("ordem", models.IntegerField(default=0)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mais_menos", "Mais/Menos"),
                            ("ranking", "Ranking"),
                            ("escala", "Escala Likert"),
                            ("forcado", "Escolha Forçada"),
                        ],
                        default="mais_menos",
                        max_length=30,
                    ),
                ),
                ("texto", models.TextField(blank=True)),
                (
                    "opcoes",
                    models.JSONField(
                        default=list, help_text="Lista de opções com mapeamento DISC"
                    ),
                ),
                (
                    "questionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questoes",
                        to="gestao_comportamental.questionarioprofiler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questão Profiler",
                "verbose_name_plural": "Questões Profiler",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="MatchComportamental",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "match_dominancia",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "match_influencia",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "match_estabilidade",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "match_conformidade",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("match_geral", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "classificacao",
                    models.CharField(
                        choices=[
                            ("excelente", "Excelente (90-100%)"),
                            ("muito_bom", "Muito Bom (75-89%)"),
                            ("bom", "Bom (60-74%)"),
                            ("razoavel", "Razoável (40-59%)"),
                            ("baixo", "Baixo (0-39%)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pontos_alinhamento", models.JSONField(default=list)),
                ("pontos_atencao", models.JSONField(default=list)),
                ("recomendacoes", models.JSONField(default=list)),
                ("analise_ia", models.TextField(blank=True)),
                (
                    "perfil_disc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="gestao_comportamental.perfildisc",
                    ),
                ),
                (
                    "perfil_ideal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="gestao_comportamental.perfilidealcargo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Comportamental",
                "verbose_name_plural": "Matches Comportamentais",
                "ordering": ["-match_geral"],
                "unique_together": {("perfil_disc", "perfil_ideal")},
            },
        ),
        migrations.CreateModel(
            name="RespostaProfiler",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("resposta", models.JSONField(default=dict)),
                (
                    "tempo_resposta",
                    models.IntegerField(default=0, help_text="Segundos"),
                ),
                (
                    "aplicacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="gestao_comportamental.aplicacaoprofiler",
                    ),
                ),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="gestao_comportamental.questaoprofiler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta Profiler",
                "verbose_name_plural": "Respostas Profiler",
                "unique_together": {("aplicacao", "questao")},
            },
        ),
    ]
