# Generated by Django 5.2.9 on 2025-12-13 02:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidenteSeguranca",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "protocolo",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "severidade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_incidente",
                    models.CharField(
                        choices=[
                            ("vazamento", "Vazamento de Dados"),
                            ("acesso_nao_autorizado", "Acesso Não Autorizado"),
                            ("perda_dados", "Perda de Dados"),
                            ("alteracao_indevida", "Alteração Indevida"),
                            ("ransomware", "Ransomware"),
                            ("phishing", "Phishing"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("dados_afetados", models.JSONField(default=list)),
                ("quantidade_titulares", models.IntegerField(blank=True, null=True)),
                ("categorias_titulares", models.JSONField(default=list)),
                ("data_ocorrencia", models.DateTimeField()),
                ("data_deteccao", models.DateTimeField()),
                ("data_contencao", models.DateTimeField(blank=True, null=True)),
                ("data_resolucao", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detectado", "Detectado"),
                            ("em_investigacao", "Em Investigação"),
                            ("contido", "Contido"),
                            ("erradicado", "Erradicado"),
                            ("recuperado", "Recuperado"),
                            ("fechado", "Fechado"),
                        ],
                        default="detectado",
                        max_length=20,
                    ),
                ),
                ("comunicado_anpd", models.BooleanField(default=False)),
                ("data_comunicacao_anpd", models.DateTimeField(blank=True, null=True)),
                ("protocolo_anpd", models.CharField(blank=True, max_length=100)),
                ("comunicado_titulares", models.BooleanField(default=False)),
                (
                    "data_comunicacao_titulares",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "metodo_comunicacao_titulares",
                    models.CharField(blank=True, max_length=100),
                ),
                ("causa_raiz", models.TextField(blank=True)),
                ("acoes_tomadas", models.JSONField(default=list)),
                ("medidas_preventivas", models.JSONField(default=list)),
                (
                    "reportado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidentes_reportados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsavel_investigacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidentes_investigados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incidente de Segurança",
                "verbose_name_plural": "Incidentes de Segurança",
                "ordering": ["-data_deteccao"],
            },
        ),
        migrations.CreateModel(
            name="RegistroAnonimizacao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("anonimizacao", "Anonimização"),
                            ("pseudonimizacao", "Pseudonimização"),
                            ("eliminacao", "Eliminação"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motivo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "modelo",
                    models.CharField(help_text="Nome do modelo Django", max_length=100),
                ),
                ("campos", models.JSONField(default=list, help_text="Campos afetados")),
                ("quantidade_registros", models.IntegerField()),
                ("data_execucao", models.DateTimeField(auto_now_add=True)),
                ("tecnica", models.CharField(max_length=100)),
                ("reversivel", models.BooleanField(default=False)),
                (
                    "executado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Anonimização",
                "verbose_name_plural": "Registros de Anonimização",
            },
        ),
        migrations.CreateModel(
            name="RegistroTratamento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "base_legal",
                    models.CharField(
                        choices=[
                            ("consentimento", "Consentimento do Titular (Art. 7, I)"),
                            (
                                "obrigacao_legal",
                                "Cumprimento de Obrigação Legal (Art. 7, II)",
                            ),
                            (
                                "administracao_publica",
                                "Administração Pública (Art. 7, III)",
                            ),
                            (
                                "estudos_pesquisa",
                                "Estudos por Órgão de Pesquisa (Art. 7, IV)",
                            ),
                            ("execucao_contrato", "Execução de Contrato (Art. 7, V)"),
                            (
                                "exercicio_direitos",
                                "Exercício Regular de Direitos (Art. 7, VI)",
                            ),
                            ("protecao_vida", "Proteção da Vida (Art. 7, VII)"),
                            ("tutela_saude", "Tutela da Saúde (Art. 7, VIII)"),
                            ("interesse_legitimo", "Interesse Legítimo (Art. 7, IX)"),
                            ("protecao_credito", "Proteção ao Crédito (Art. 7, X)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "finalidade",
                    models.CharField(
                        choices=[
                            ("gestao_rh", "Gestão de Recursos Humanos"),
                            ("folha_pagamento", "Processamento de Folha de Pagamento"),
                            ("recrutamento", "Recrutamento e Seleção"),
                            ("treinamento", "Treinamento e Desenvolvimento"),
                            ("avaliacao", "Avaliação de Desempenho"),
                            ("beneficios", "Gestão de Benefícios"),
                            ("saude_seguranca", "Saúde e Segurança do Trabalho"),
                            ("obrigacoes_legais", "Cumprimento de Obrigações Legais"),
                            ("comunicacao", "Comunicação Interna"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "dados_pessoais",
                    models.JSONField(
                        default=list,
                        help_text="Lista de categorias de dados pessoais tratados",
                    ),
                ),
                (
                    "dados_sensiveis",
                    models.JSONField(
                        default=list,
                        help_text="Lista de dados sensíveis tratados (Art. 5, II)",
                    ),
                ),
                (
                    "categorias_titulares",
                    models.JSONField(
                        default=list,
                        help_text="Categorias de titulares (colaboradores, candidatos, etc.)",
                    ),
                ),
                (
                    "destinatarios",
                    models.JSONField(
                        default=list,
                        help_text="Organizações com quem dados são compartilhados",
                    ),
                ),
                ("transferencia_internacional", models.BooleanField(default=False)),
                ("paises_transferencia", models.JSONField(blank=True, default=list)),
                (
                    "prazo_retencao_dias",
                    models.IntegerField(help_text="Prazo de retenção em dias"),
                ),
                ("justificativa_retencao", models.TextField()),
                (
                    "medidas_seguranca",
                    models.JSONField(
                        default=list,
                        help_text="Medidas técnicas e organizacionais aplicadas",
                    ),
                ),
                ("controlador", models.CharField(max_length=200)),
                ("operador", models.CharField(blank=True, max_length=200)),
                ("encarregado_dpo", models.CharField(max_length=200)),
                ("data_aprovacao", models.DateTimeField(blank=True, null=True)),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_aprovados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Tratamento",
                "verbose_name_plural": "Registros de Tratamento",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RelatorioImpacto",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("titulo", models.CharField(max_length=200)),
                ("versao", models.CharField(max_length=20)),
                ("descricao_tratamento", models.TextField()),
                ("necessidade_proporcionalidade", models.TextField()),
                ("riscos_identificados", models.JSONField(default=list)),
                (
                    "probabilidade_risco",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "impacto_risco",
                    models.CharField(
                        choices=[
                            ("baixo", "Baixo"),
                            ("medio", "Médio"),
                            ("alto", "Alto"),
                        ],
                        max_length=20,
                    ),
                ),
                ("medidas_mitigadoras", models.JSONField(default=list)),
                ("riscos_residuais", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("em_revisao", "Em Revisão"),
                            ("aprovado", "Aprovado"),
                            ("arquivado", "Arquivado"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                ("data_aprovacao", models.DateTimeField(blank=True, null=True)),
                ("parecer_dpo", models.TextField(blank=True)),
                ("data_parecer_dpo", models.DateTimeField(blank=True, null=True)),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ripd_aprovados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "elaborado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ripd_elaborados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registro_tratamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relatorios_impacto",
                        to="lgpd.registrotratamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório de Impacto (RIPD)",
                "verbose_name_plural": "Relatórios de Impacto (RIPD)",
            },
        ),
        migrations.CreateModel(
            name="SolicitacaoTitular",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "protocolo",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("email_contato", models.EmailField(max_length=254)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("confirmacao", "Confirmação de Tratamento (Art. 18, I)"),
                            ("acesso", "Acesso aos Dados (Art. 18, II)"),
                            ("correcao", "Correção de Dados (Art. 18, III)"),
                            (
                                "anonimizacao",
                                "Anonimização/Bloqueio/Eliminação (Art. 18, IV)",
                            ),
                            ("portabilidade", "Portabilidade dos Dados (Art. 18, V)"),
                            ("eliminacao", "Eliminação de Dados (Art. 18, VI)"),
                            (
                                "info_compartilhamento",
                                "Informação sobre Compartilhamento (Art. 18, VII)",
                            ),
                            (
                                "info_nao_consentimento",
                                "Possibilidade de Não Consentir (Art. 18, VIII)",
                            ),
                            ("revogacao", "Revogação de Consentimento (Art. 18, IX)"),
                            ("oposicao", "Oposição ao Tratamento (Art. 18, §2)"),
                            (
                                "revisao_decisao",
                                "Revisão de Decisão Automatizada (Art. 20)",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                ("descricao", models.TextField()),
                ("dados_solicitados", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_analise", "Em Análise"),
                            ("aguardando_info", "Aguardando Informações"),
                            ("em_execucao", "Em Execução"),
                            ("concluida", "Concluída"),
                            ("negada", "Negada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("data_limite", models.DateTimeField()),
                ("resposta", models.TextField(blank=True)),
                ("data_resposta", models.DateTimeField(blank=True, null=True)),
                ("justificativa_negativa", models.TextField(blank=True)),
                (
                    "arquivo_resposta",
                    models.FileField(
                        blank=True, null=True, upload_to="lgpd/respostas/"
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes_atendidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "titular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_lgpd",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação do Titular",
                "verbose_name_plural": "Solicitações dos Titulares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TermoConsentimento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("titulo", models.CharField(max_length=200)),
                ("versao", models.CharField(max_length=20)),
                ("conteudo", models.TextField()),
                ("finalidades", models.JSONField(default=list)),
                ("data_vigencia_inicio", models.DateField()),
                ("data_vigencia_fim", models.DateField(blank=True, null=True)),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Termo de Consentimento",
                "verbose_name_plural": "Termos de Consentimento",
                "unique_together": {("titulo", "versao")},
            },
        ),
        migrations.CreateModel(
            name="ConsentimentoTitular",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("finalidades_aceitas", models.JSONField(default=list)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("data_consentimento", models.DateTimeField(auto_now_add=True)),
                ("data_revogacao", models.DateTimeField(blank=True, null=True)),
                ("motivo_revogacao", models.TextField(blank=True)),
                ("hash_consentimento", models.CharField(editable=False, max_length=64)),
                (
                    "titular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consentimentos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "termo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consentimentos",
                        to="lgpd.termoconsentimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consentimento do Titular",
                "verbose_name_plural": "Consentimentos dos Titulares",
                "ordering": ["-data_consentimento"],
            },
        ),
        migrations.CreateModel(
            name="LogAcessoDados",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("modelo", models.CharField(max_length=100)),
                ("objeto_id", models.CharField(max_length=100)),
                ("campos_acessados", models.JSONField(default=list)),
                (
                    "operacao",
                    models.CharField(
                        choices=[
                            ("visualizar", "Visualizar"),
                            ("exportar", "Exportar"),
                            ("editar", "Editar"),
                            ("excluir", "Excluir"),
                            ("compartilhar", "Compartilhar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("finalidade", models.CharField(blank=True, max_length=200)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("endpoint", models.CharField(max_length=500)),
                ("data_acesso", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Acesso a Dados",
                "verbose_name_plural": "Logs de Acesso a Dados",
                "ordering": ["-data_acesso"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "data_acesso"],
                        name="lgpd_logace_usuario_c12011_idx",
                    ),
                    models.Index(
                        fields=["modelo", "objeto_id"],
                        name="lgpd_logace_modelo_965bea_idx",
                    ),
                ],
            },
        ),
    ]
