# Generated by Django 5.1.3 on 2025-12-12 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_auditlog_options_alter_company_options_and_more"),
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={"verbose_name": "Contrato", "verbose_name_plural": "Contratos"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Projeto", "verbose_name_plural": "Projetos"},
        ),
        migrations.AlterModelOptions(
            name="projectmember",
            options={
                "verbose_name": "Membro do Projeto",
                "verbose_name_plural": "Membros do Projeto",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["kanban_order", "-created_at"],
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
            },
        ),
        migrations.AlterModelOptions(
            name="taskcomment",
            options={
                "verbose_name": "Comentário na Tarefa",
                "verbose_name_plural": "Comentários nas Tarefas",
            },
        ),
        migrations.AlterModelOptions(
            name="timelog",
            options={
                "verbose_name": "Registro de Tempo",
                "verbose_name_plural": "Registros de Tempo",
            },
        ),
        migrations.AlterField(
            model_name="contract",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("signed", "Assinado"),
                    ("active", "Ativo"),
                    ("completed", "Concluído"),
                    ("cancelled", "Cancelado"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Planejamento"),
                    ("active", "Ativo"),
                    ("paused", "Pausado"),
                    ("completed", "Concluído"),
                    ("cancelled", "Cancelarado"),
                ],
                default="planning",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Baixo"),
                    ("medium", "Médio"),
                    ("high", "Alto"),
                    ("urgent", "Urgente"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("todo", "To Do"),
                    ("in_progress", "Em Progresso"),
                    ("review", "Review"),
                    ("done", "Concluído"),
                ],
                default="backlog",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="taskcomment",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="timelog",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Tenant) a qual este registro pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_company",
                to="core.company",
            ),
        ),
    ]
