# Generated by Django 5.1.3 on 2025-12-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0002_alter_contract_options_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("fixed_price", "Preço Fixo"),
                    ("hourly", "Por Hora"),
                    ("retainer", "Retentor"),
                    ("T&M", "Tempo & Material"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Planejamento"),
                    ("active", "Ativo"),
                    ("paused", "Pausado"),
                    ("completed", "Concluído"),
                    ("cancelled", "Cancelado"),
                ],
                default="planning",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("todo", "A Fazer"),
                    ("in_progress", "Em Progresso"),
                    ("review", "Revisão"),
                    ("done", "Concluído"),
                ],
                default="backlog",
                max_length=20,
            ),
        ),
    ]
